"""Catalog generator type: a2_direct_and_inverse_variation_direct_and_inverse_variation."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_direct_and_inverse_variation_direct_and_inverse_variation")
