"""Graphing catalog type: a2_quadratic_functions_and_inequalities_graphing_quadratic_inequalities."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_quadratic_functions_and_inequalities_graphing_quadratic_inequalities")
