from .base import entry

COURSE_ID = "algebra_1"

CATEGORY_ORDER: tuple[str, ...] = (
    "Pre-Algebra — Beginning Algebra",
    "Algebra 1 — Beginning Algebra",
    "Pre-Algebra — Equations",
    "Algebra 1 — Equations",
    "Pre-Algebra — Inequalities",
    "Algebra 1 — Inequalities",
    "Pre-Algebra — Proportions and Similarity",
    "Pre-Algebra — Percents",
    "Algebra 1 — Relations and Introduction to Functions",
    "Pre-Algebra — Linear Equations and Inequalities",
    "Algebra 1 — Linear Equations and Inequalities",
    "Algebra 1 — Direct and inverse variation",
    "Algebra 1 — Systems of Equations and Inequalities",
    "Pre-Algebra — Factors and Exponents",
    "Algebra 1 — Exponents",
    "Algebra 1 — Polynomials",
    "Algebra 1 — Quadratic Functions",
    "Pre-Algebra — Right Triangles",
    "Algebra 1 — Radical Expressions",
    "Algebra 1 — Rational Expressions",
    "Algebra 1 — Beginning Trigonometry",
    "Pre-Algebra — Statistics",
)

CATALOG: tuple = (
    entry(
        "verbal_expressions",
        "Verbal expressions",
        "Pre-Algebra — Beginning Algebra",
        generator="verbal_expressions",
        instruction_latex=r"\text{Write as an algebraic expression.}",
        instruction_text="Write as an algebraic expression.",
    ),
    entry(
        "order_of_operations",
        "Order of operations",
        "Pre-Algebra — Beginning Algebra",
        generator="order_of_operations",
        instruction_latex=r"\text{Evaluate.}",
        instruction_text="Evaluate.",
    ),
    entry(
        "sets_of_numbers",
        "Sets of numbers",
        "Algebra 1 — Beginning Algebra",
        generator="sets_of_numbers",
        instruction_latex=r"\text{To which set(s) of numbers does each number belong?}",
        instruction_text="To which set(s) of numbers does each number belong?",
    ),
    entry(
        "rational_add_subtract",
        "Adding and subtracting rational numbers",
        "Algebra 1 — Beginning Algebra",
        generator="rational_add_subtract",
        instruction_latex=r"\text{Evaluate.}",
        instruction_text="Evaluate.",
    ),
    entry(
        "rational_multiply",
        "Multiplying rational numbers",
        "Algebra 1 — Beginning Algebra",
        generator="rational_multiply",
        instruction_latex=r"\text{Evaluate.}",
        instruction_text="Evaluate.",
    ),
    entry(
        "rational_divide",
        "Dividing rational numbers",
        "Algebra 1 — Beginning Algebra",
        generator="rational_divide",
        instruction_latex=r"\text{Evaluate.}",
        instruction_text="Evaluate.",
    ),
    entry(
        "distributive_property",
        "The Distributive Property",
        "Pre-Algebra — Beginning Algebra",
        generator="distributive_property",
        instruction_latex=r"\text{Evaluate.}",
        instruction_text="Evaluate.",
    ),
    entry(
        "one_step_equations",
        "One-step equations",
        "Pre-Algebra — Equations",
        generator="one_step_equations",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "two_step_equations",
        "Two-step equations",
        "Pre-Algebra — Equations",
        generator="two_step_equations",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "multi_step_equations",
        "Multi-step equations",
        "Algebra 1 — Equations",
        generator="multi_step_equations",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "absolute_value_equations",
        "Absolute value equations",
        "Algebra 1 — Equations",
        generator="absolute_value_equations",
        instruction_latex=r"\text{Solve.}",
        instruction_text="Solve.",
    ),
    entry(
        "mixture_word_problems",
        "Mixture word problems",
        "Algebra 1 — Equations",
        generator="wp_mixture",
        instruction_latex=r"\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    entry(
        "distance_rate_time_word_problems",
        "Distance, rate, time word problems",
        "Algebra 1 — Equations",
        generator="wp_distance_rate_time",
        instruction_latex=r"\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    entry(
        "work_word_problems",
        "Work word problems",
        "Algebra 1 — Equations",
        generator="wp_work",
        instruction_latex=r"\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    entry(
        "age_word_problems",
        "Age word problems",
        "Algebra 1 — Equations",
        generator="wp_age",
        instruction_latex=r"\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    entry(
        "coin_word_problems",
        "Coin word problems",
        "Algebra 1 — Equations",
        generator="wp_coin",
        instruction_latex=r"\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    entry(
        "consecutive_integers_word_problems",
        "Consecutive integers word problems",
        "Algebra 1 — Equations",
        generator="wp_consecutive_integers",
        instruction_latex=r"\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    entry(
        "percent_word_problems",
        "Percent word problems",
        "Algebra 1 — Equations",
        generator="wp_percent",
        instruction_latex=r"\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    entry(
        "literal_equations",
        "Literal equations",
        "Algebra 1 — Equations",
        generator="literal_equations",
        instruction_latex=r"\text{Solve for the indicated variable.}",
        instruction_text="Solve for the indicated variable.",
    ),
    entry(
        "graphing_single_variable_inequalities",
        "Graphing single-variable inequalities",
        "Pre-Algebra — Inequalities",
        generator="graph_single_variable_inequality",
        instruction_latex=r"\text{Graph the following on the number line.}",
        instruction_text="Graph the following on the number line.",
    ),
    entry(
        "one_step_inequalities",
        "One-step inequalities",
        "Pre-Algebra — Inequalities",
        generator="one_step_inequalities",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "two_step_inequalities",
        "Two-step inequalities",
        "Pre-Algebra — Inequalities",
        generator="two_step_inequalities",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "multi_step_inequalities",
        "Multi-step inequalities",
        "Algebra 1 — Inequalities",
        generator="multi_step_inequalities",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "compound_inequalities",
        "Compound inequalities",
        "Algebra 1 — Inequalities",
        generator="compound_inequalities",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "absolute_value_inequalities",
        "Absolute value inequalities",
        "Algebra 1 — Inequalities",
        generator="absolute_value_inequalities",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "solving_proportions",
        "Solving proportions",
        "Pre-Algebra — Proportions and Similarity",
        generator="solving_proportions",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "percents",
        "Percents",
        "Pre-Algebra — Percents",
        generator="percents",
        instruction_latex=r"\text{Find the value.}",
        instruction_text="Find the value.",
    ),
    entry(
        "percent_of_change",
        "Percent of change",
        "Pre-Algebra — Percents",
        generator="percent_of_change",
        instruction_latex=r"\text{Find the percent of change.}",
        instruction_text="Find the percent of change.",
    ),
    entry(
        "discrete_relations",
        "Discrete relations",
        "Algebra 1 — Relations and Introduction to Functions",
        generator="discrete_relations",
        instruction_latex=r"\text{Evaluate the relation.}",
        instruction_text="Evaluate the relation.",
    ),
    entry(
        "continuous_relations",
        "Continuous relations",
        "Algebra 1 — Relations and Introduction to Functions",
        generator="continuous_relations",
        instruction_latex=r"\text{Evaluate the relation.}",
        instruction_text="Evaluate the relation.",
    ),
    entry(
        "evaluating_graphing_functions",
        "Evaluating and graphing functions",
        "Algebra 1 — Relations and Introduction to Functions",
        generator="evaluating_graphing_functions",
        instruction_latex=r"\text{Evaluate.}",
        instruction_text="Evaluate.",
    ),
    entry(
        "slope",
        "Slope",
        "Pre-Algebra — Linear Equations and Inequalities",
        generator="slope",
        instruction_latex=r"\text{Find the slope.}",
        instruction_text="Find the slope.",
    ),
    entry(
        "more_on_slope",
        "More on slope",
        "Algebra 1 — Linear Equations and Inequalities",
        generator="more_on_slope",
        instruction_latex=r"\text{Answer each question about slope.}",
        instruction_text="Answer each question about slope.",
    ),
    entry(
        "graphing_linear_equations",
        "Graphing linear equations",
        "Pre-Algebra — Linear Equations and Inequalities",
        generator="graph_linear_equation",
        instruction_latex=r"\text{Graph the following equations.}",
        instruction_text="Graph the following equations.",
    ),
    entry(
        "writing_linear_equations",
        "Writing linear equations",
        "Pre-Algebra — Linear Equations and Inequalities",
        generator="writing_linear_equations",
        instruction_latex=r"\text{Write the equation.}",
        instruction_text="Write the equation.",
    ),
    entry(
        "graphing_linear_inequalities",
        "Graphing linear inequalities",
        "Pre-Algebra — Linear Equations and Inequalities",
        generator="graph_linear_inequality",
        instruction_latex=r"\text{Graph the following inequalities.}",
        instruction_text="Graph the following inequalities.",
    ),
    entry(
        "graphing_absolute_value_equations",
        "Graphing absolute value equations",
        "Algebra 1 — Linear Equations and Inequalities",
        generator="graph_absolute_value",
        instruction_latex=r"\text{Graph the following equations.}",
        instruction_text="Graph the following equations.",
    ),
    entry(
        "direct_inverse_variation",
        "Direct and inverse variation",
        "Algebra 1 — Direct and inverse variation",
        generator="direct_inverse_variation",
        instruction_latex=r"\text{Write the variation equation.}",
        instruction_text="Write the variation equation.",
    ),
    entry(
        "systems_graphing",
        "Solving by graphing",
        "Algebra 1 — Systems of Equations and Inequalities",
        generator="graph_system",
        instruction_latex=r"\text{Solve the system.}",
        instruction_text="Solve the system.",
    ),
    entry(
        "systems_elimination",
        "Solving by elimination",
        "Algebra 1 — Systems of Equations and Inequalities",
        generator="systems_elimination",
        instruction_latex=r"\text{Solve the system.}",
        instruction_text="Solve the system.",
    ),
    entry(
        "systems_substitution",
        "Solving by substitution",
        "Algebra 1 — Systems of Equations and Inequalities",
        generator="systems_substitution",
        instruction_latex=r"\text{Solve the system.}",
        instruction_text="Solve the system.",
    ),
    entry(
        "graphing_systems_of_inequalities",
        "Graphing systems of inequalities",
        "Algebra 1 — Systems of Equations and Inequalities",
        generator="graph_system_inequalities",
        instruction_latex=r"\text{Graph the following systems.}",
        instruction_text="Graph the following systems.",
    ),
    entry(
        "systems_word_problems",
        "Word problems",
        "Algebra 1 — Systems of Equations and Inequalities",
        generator="wp_systems",
        instruction_latex=r"\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    entry(
        "properties_of_exponents",
        "Properties of exponents",
        "Pre-Algebra — Factors and Exponents",
        generator="properties_of_exponents",
        instruction_latex=r"\text{Simplify.}",
        instruction_text="Simplify.",
    ),
    entry(
        "graphing_exponential_functions",
        "Graphing exponential functions",
        "Algebra 1 — Exponents",
        generator="graph_exponential",
        instruction_latex=r"\text{Graph the following functions.}",
        instruction_text="Graph the following functions.",
    ),
    entry(
        "scientific_notation_write",
        "Writing scientific notation",
        "Pre-Algebra — Factors and Exponents",
        generator="scientific_notation_write",
        instruction_latex=r"\text{Write in scientific notation.}",
        instruction_text="Write in scientific notation.",
    ),
    entry(
        "scientific_notation_operations",
        "Operations and scientific notation",
        "Pre-Algebra — Factors and Exponents",
        generator="scientific_notation_operations",
        instruction_latex=r"\text{Evaluate. Write in scientific notation.}",
        instruction_text="Evaluate. Write in scientific notation.",
    ),
    entry(
        "scientific_notation_add_subtract",
        "Addition/Subtraction and scientific notation",
        "Algebra 1 — Exponents",
        generator="scientific_notation_add_subtract",
        instruction_latex=r"\text{Evaluate. Write in scientific notation.}",
        instruction_text="Evaluate. Write in scientific notation.",
    ),
    entry(
        "exponential_growth_decay",
        "Discrete exponential growth and decay word problems",
        "Algebra 1 — Exponents",
        generator="exponential_growth_decay",
        instruction_latex=r"\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    entry(
        "polynomial_naming",
        "Naming",
        "Algebra 1 — Polynomials",
        generator="polynomial_naming",
        instruction_latex=r"\text{Name the polynomial.}",
        instruction_text="Name the polynomial.",
    ),
    entry(
        "polynomial_add_subtract",
        "Adding and subtracting",
        "Algebra 1 — Polynomials",
        generator="polynomial_add_subtract",
        instruction_latex=r"\text{Simplify.}",
        instruction_text="Simplify.",
    ),
    entry(
        "polynomial_multiply",
        "Multiplying",
        "Algebra 1 — Polynomials",
        generator="polynomial_multiply",
        instruction_latex=r"\text{Multiply.}",
        instruction_text="Multiply.",
    ),
    entry(
        "polynomial_multiply_special",
        "Multiplying special cases",
        "Algebra 1 — Polynomials",
        generator="polynomial_multiply_special",
        instruction_latex=r"\text{Multiply.}",
        instruction_text="Multiply.",
    ),
    entry(
        "polynomial_factoring_common_factor",
        "Common factor only",
        "Algebra 1 — Polynomials",
        subcategory="Factoring",
        generator="polynomial_factoring_common_factor",
        instruction_latex=r"\text{Factor completely.}",
        instruction_text="Factor completely.",
    ),
    entry(
        "polynomial_factoring_special_cases",
        "Special cases",
        "Algebra 1 — Polynomials",
        subcategory="Factoring",
        generator="polynomial_factoring_special_cases",
        instruction_latex=r"\text{Factor using special products.}",
        instruction_text="Factor using special products.",
    ),
    entry(
        "polynomial_factoring_grouping",
        "By grouping",
        "Algebra 1 — Polynomials",
        subcategory="Factoring",
        generator="polynomial_factoring_grouping",
        instruction_latex=r"\text{Factor completely.}",
        instruction_text="Factor completely.",
    ),
    entry(
        "graphing_quadratic_functions",
        "Graphing",
        "Algebra 1 — Quadratic Functions",
        generator="graph_quadratic",
        instruction_latex=r"\text{Graph the following functions.}",
        instruction_text="Graph the following functions.",
    ),
    entry(
        "quadratic_solve_by_graphing",
        "Solving equations by graphing",
        "Algebra 1 — Quadratic Functions",
        generator="solve_polynomial_by_graphing",
        instruction_latex=r"\text{Solve by graphing.}",
        instruction_text="Solve by graphing.",
    ),
    entry(
        "graphing_quadratic_inequalities",
        "Graphing quadratic inequalities",
        "Algebra 1 — Quadratic Functions",
        generator="graph_quadratic_inequality",
        instruction_latex=r"\text{Graph the following inequalities.}",
        instruction_text="Graph the following inequalities.",
    ),
    entry(
        "quadratic_square_roots",
        "Solving equations by taking square roots",
        "Algebra 1 — Quadratic Functions",
        generator="quadratic_square_roots",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "quadratic_factoring_equations",
        "Solving equations by factoring",
        "Algebra 1 — Quadratic Functions",
        generator="quadratic_factoring_equations",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "quadratic_formula",
        "Solving equations with the Quadratic Formula",
        "Algebra 1 — Quadratic Functions",
        generator="quadratic_formula",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "quadratic_discriminant",
        "Understanding the discriminant",
        "Algebra 1 — Quadratic Functions",
        generator="quadratic_discriminant",
        instruction_latex=r"\text{Find the discriminant and describe the roots.}",
        instruction_text="Find the discriminant and describe the roots.",
    ),
    entry(
        "quadratic_completing_square_constant",
        "Completing the square by finding the constant",
        "Algebra 1 — Quadratic Functions",
        generator="quadratic_completing_square_constant",
        instruction_latex=r"\text{Find the value of } c.",
        instruction_text="Find the value of c.",
    ),
    entry(
        "quadratic_completing_square_solve",
        "Solving equations by completing the square",
        "Algebra 1 — Quadratic Functions",
        generator="quadratic_completing_square_solve",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "radical_distance_formula",
        "The Distance Formula",
        "Pre-Algebra — Right Triangles",
        generator="radical_distance_formula",
        instruction_latex=r"\text{Find the distance.}",
        instruction_text="Find the distance.",
    ),
    entry(
        "radical_midpoint_formula",
        "The Midpoint Formula",
        "Pre-Algebra — Linear Equations and Inequalities",
        generator="radical_midpoint_formula",
        instruction_latex=r"\text{Find the midpoint.}",
        instruction_text="Find the midpoint.",
    ),
    entry(
        "radical_add_subtract",
        "Adding and subtracting",
        "Algebra 1 — Radical Expressions",
        generator="radical_add_subtract",
        instruction_latex=r"\text{Simplify.}",
        instruction_text="Simplify.",
    ),
    entry(
        "radical_multiply",
        "Multiplying",
        "Algebra 1 — Radical Expressions",
        generator="radical_multiply",
        instruction_latex=r"\text{Simplify.}",
        instruction_text="Simplify.",
    ),
    entry(
        "radical_divide",
        "Dividing",
        "Algebra 1 — Radical Expressions",
        generator="radical_divide",
        instruction_latex=r"\text{Simplify.}",
        instruction_text="Simplify.",
    ),
    entry(
        "radical_equations",
        "Equations",
        "Algebra 1 — Radical Expressions",
        generator="radical_equations",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    # Hand-written generators (see verify_curriculum_types.HAND_WRITTEN)
    entry(
        "rational_simplification",
        "Simplifying and excluded values",
        "Algebra 1 — Rational Expressions",
        generator="rational_simplification",
        instruction_latex=r"\text{Simplify. State any excluded values.}",
        instruction_text="Simplify. State any excluded values.",
    ),
    entry(
        "rational_expression_simplification",
        "Adding and subtracting",
        "Algebra 1 — Rational Expressions",
        generator="rational_expression_simplification",
        instruction_latex=r"\text{Combine and simplify.}",
        instruction_text="Combine and simplify.",
    ),
    entry(
        "rational_expression_multiply_divide",
        "Multiplying and dividing",
        "Algebra 1 — Rational Expressions",
        generator="rational_expression_multiply_divide",
        instruction_latex=r"\text{Simplify.}",
        instruction_text="Simplify.",
    ),
    entry(
        "rational_expressions_equations",
        "Equations",
        "Algebra 1 — Rational Expressions",
        generator="rational_equations",
        instruction_latex=r"\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    entry(
        "finding_sine_cosine_tangent",
        "Finding sine, cosine, tangent",
        "Algebra 1 — Beginning Trigonometry",
        generator="geo_right_triangle_trig_ratio",
        instruction_latex=r"\text{Find the trigonometric ratio.}",
        instruction_text="Find the trigonometric ratio.",
    ),
    entry(
        "finding_angles",
        "Finding angles",
        "Algebra 1 — Beginning Trigonometry",
        generator="finding_angles",
        instruction_latex=r"\text{Find the angle measure.}",
        instruction_text="Find the angle measure.",
    ),
    entry(
        "find_missing_sides_of_triangles",
        "Find missing sides of triangles",
        "Algebra 1 — Beginning Trigonometry",
        generator="geo_right_triangle_trig_side",
        instruction_latex=r"\text{Find the missing side.}",
        instruction_text="Find the missing side.",
    ),
    entry(
        "visualizing_data",
        "Visualizing data",
        "Pre-Algebra — Statistics",
        generator="stats_dot_plot_read",
        instruction_latex=r"\text{Interpret the display.}",
        instruction_text="Interpret the display.",
    ),
    entry(
        "center_and_spread",
        "Center and spread",
        "Pre-Algebra — Statistics",
        generator="stats_center_spread",
        instruction_latex=r"\text{Find the measure.}",
        instruction_text="Find the measure.",
    ),
    entry(
        "scatter_plots",
        "Scatter plots",
        "Pre-Algebra — Statistics",
        generator="scatter_plot_interpret",
        instruction_latex=r"\text{Interpret the scatter plot.}",
        instruction_text="Interpret the scatter plot.",
    ),
    entry(
        "using_statistical_models",
        "Using statistical models",
        "Pre-Algebra — Statistics",
        generator="stats_statistical_model",
        instruction_latex=r"\text{Use the linear model to make a prediction.}",
        instruction_text="Use the linear model to make a prediction.",
    ),
)
