COURSE_ID = "algebra_2"

CATEGORY_ORDER: tuple[str, ...] = (
    # OpenStax Intermediate Algebra 2e spine + supplemental
    'Algebra 2 — Beginning Algebra',  # Foundations
    'Algebra 2 — Equations and Inequalities',
    'Algebra 2 — Relations and Introduction to Functions',  # Graphs and Functions
    'Algebra 2 — Linear Relations and Functions',
    'Algebra 2 — Systems of Equations and Inequalities',
    'Algebra 2 — Polynomial Functions',
    'Algebra 2 — Quadratic Functions and Inequalities',
    'Algebra 2 — Rational Expressions',
    'Algebra 2 — Radical Functions and Rational Exponents',  # Roots and Radicals
    'Algebra 2 — Exponential and Logarithmic Expressions',
    'Algebra 2 — Conic Sections',
    'Algebra 2 — Sequences and Series',
    # Supplemental
    'Algebra 2 — Matrices',
    'Algebra 2 — Complex Numbers',
    'Algebra 2 — Trigonometry',
    'Algebra 2 — Probability and Statistics',
    'Algebra 2 — Direct and Inverse Variation',
    'Algebra 2 — General Functions',
)

from .base import TypeCatalogEntry, resolve_instruction_latex, resolve_instruction_text



def _a2(
    chapter: str,
    id: str,
    name: str,
    *,
    instruction_latex: str = "",
    instruction_text: str = "",
    count_default: int = 10,
    generator: str = "scaffold",
) -> TypeCatalogEntry:
    return TypeCatalogEntry(
        id=id,
        name=name,
        category=f"Algebra 2 — {chapter}",
        generator=generator,
        description=f"Practice {name.lower()}.",
        instruction_latex=resolve_instruction_latex(instruction_latex, instruction_text),
        instruction_text=resolve_instruction_text(instruction_text),
        count_default=count_default,
    )


CATALOG: tuple[TypeCatalogEntry, ...] = (
    # Beginning Algebra
    _a2("Beginning Algebra", "a2_beginning_algebra_order_of_operations", "Order of operations", generator="order_of_operations", instruction_latex="\\text{Evaluate.}", instruction_text="Evaluate."),
    _a2(
        "Beginning Algebra",
        "a2_beginning_algebra_simplifying_algebraic_expressions",
        "Simplifying algebraic expressions",
        generator="expand_simplify",
        instruction_latex="\\text{Expand and simplify.}",
        instruction_text="Expand and simplify.",
    ),
    # Equations and Inequalities
    _a2("Equations and Inequalities", "a2_equations_and_inequalities_multi_step_equations", "Multi-step equations", generator="multi_step_equations", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    _a2("Equations and Inequalities", "a2_equations_and_inequalities_work_word_problems", "Work word problems", generator="wp_work", instruction_latex="\\text{Solve the problem.}", instruction_text="Solve the problem.", count_default=5),
    _a2("Equations and Inequalities", "a2_equations_and_inequalities_distance_rate_time_word_problems", "Distance, rate, time word problems", generator="wp_distance_rate_time", instruction_latex="\\text{Solve the problem.}", instruction_text="Solve the problem.", count_default=5),
    _a2("Equations and Inequalities", "a2_equations_and_inequalities_mixture_word_problems", "Mixture word problems", generator="wp_mixture", instruction_latex="\\text{Solve the problem.}", instruction_text="Solve the problem.", count_default=5),
    _a2("Equations and Inequalities", "a2_equations_and_inequalities_absolute_value_equations", "Absolute value equations", generator="absolute_value_equations", instruction_latex="\\text{Solve.}", instruction_text="Solve."),
    _a2("Equations and Inequalities", "a2_equations_and_inequalities_multi_step_inequalities", "Multi-step inequalities", generator="multi_step_inequalities", instruction_latex="\\text{Solve the inequality.}", instruction_text="Solve the inequality."),
    _a2("Equations and Inequalities", "a2_equations_and_inequalities_compound_inequalities", "Compound inequalities", generator="compound_inequalities", instruction_latex="\\text{Solve the inequality.}", instruction_text="Solve the inequality."),
    _a2("Equations and Inequalities", "a2_equations_and_inequalities_absolute_value_inequalities", "Absolute value inequalities", generator="absolute_value_inequalities", instruction_latex="\\text{Solve the inequality.}", instruction_text="Solve the inequality."),
    # Relations and Introduction to Functions
    _a2("Relations and Introduction to Functions", "a2_relations_and_introduction_to_functions_discrete_relations", "Discrete relations", generator="discrete_relations", instruction_text="Identify the relation."),
    _a2("Relations and Introduction to Functions", "a2_relations_and_introduction_to_functions_continuous_relations", "Continuous relations", generator="continuous_relations", instruction_text="Evaluate the relation."),
    _a2("Relations and Introduction to Functions", "a2_relations_and_introduction_to_functions_evaluating_and_graphing_functions", "Evaluating and graphing functions", generator="evaluating_graphing_functions", instruction_text="Evaluate or graph."),
    # Linear Relations and Functions
    _a2("Linear Relations and Functions", "a2_linear_relations_and_functions_graphing_linear_equations", "Graphing linear equations", generator="graph_linear_equation", instruction_latex="\\text{Graph the following equations.}", instruction_text="Graph the following equations."),
    _a2("Linear Relations and Functions", "a2_linear_relations_and_functions_writing_linear_equations", "Writing linear equations", generator="writing_linear_equations", instruction_text="Write the equation."),
    _a2("Linear Relations and Functions", "a2_linear_relations_and_functions_graphing_absolute_value_equations", "Graphing absolute value equations", generator="graph_absolute_value", instruction_latex="\\text{Graph the following equations.}", instruction_text="Graph the following equations."),
    _a2("Linear Relations and Functions", "a2_linear_relations_and_functions_graphing_linear_inequalities", "Graphing linear inequalities", generator="graph_linear_inequality", instruction_latex="\\text{Graph the following inequalities.}", instruction_text="Graph the following inequalities."),
    # Direct and Inverse Variation
    _a2("Direct and Inverse Variation", "a2_direct_and_inverse_variation_direct_and_inverse_variation", "Direct and inverse variation", generator="direct_inverse_variation", instruction_text="Solve the problem."),
    # Systems of Equations and Inequalities
    _a2("Systems of Equations and Inequalities", "a2_systems_of_equations_and_inequalities_graphing_systems_of_linear_inequalities", "Graphing systems of linear inequalities", generator="graph_system_inequalities", instruction_latex="\\text{Graph the following systems.}", instruction_text="Graph the following systems."),
    _a2("Systems of Equations and Inequalities", "a2_systems_of_equations_and_inequalities_solving_systems_by_graphing_2_variables", "Solving systems by graphing (2 variables)", generator="graph_system", instruction_text="Solve the system."),
    _a2("Systems of Equations and Inequalities", "a2_systems_of_equations_and_inequalities_solving_systems_by_elimination_2_variables", "Solving systems by elimination (2 variables)", generator="systems_elimination", instruction_text="Solve the system."),
    _a2("Systems of Equations and Inequalities", "a2_systems_of_equations_and_inequalities_solving_systems_by_substitution_2_variables", "Solving systems by substitution (2 variables)", generator="systems_substitution", instruction_text="Solve the system."),
    _a2("Systems of Equations and Inequalities", "a2_systems_of_equations_and_inequalities_systems_of_equations_word_problems_2_variables", "Systems of equations word problems (2 variables)", generator="wp_systems", instruction_latex="\\text{Solve the problem.}", instruction_text="Solve the problem.", count_default=5),
    _a2("Systems of Equations and Inequalities", "a2_systems_of_equations_and_inequalities_points_in_three_dimensions", "Points in three dimensions", generator="points_three_dimensions", instruction_text="Identify the point."),
    _a2("Systems of Equations and Inequalities", "a2_systems_of_equations_and_inequalities_planes", "Planes", generator="planes", instruction_text="Identify the plane."),
    _a2("Systems of Equations and Inequalities", "a2_systems_of_equations_and_inequalities_solving_systems_with_three_variables", "Solving systems with three variables", generator="system_three_variables", instruction_text="Solve the system."),
    # Matrices
    _a2("Matrices", "a2_matrices_operations", "Operations", generator="matrix_operations", instruction_latex="\\text{Evaluate.}", instruction_text="Evaluate."),
    _a2("Matrices", "a2_matrices_determinants", "Determinants", generator="matrix_operations", instruction_text="Find the determinant."),
    _a2("Matrices", "a2_matrices_inverses", "Inverses", generator="matrix_inverse", instruction_text="Find the inverse."),
    _a2("Matrices", "a2_matrices_cramers_rule", "Cramer's Rule", generator="matrix_cramers_rule", instruction_text="Solve the system."),
    _a2("Matrices", "a2_matrices_equations", "Equations", generator="matrix_operations", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    _a2("Matrices", "a2_matrices_geometric_transformations", "Geometric transformations", generator="matrix_transformation", instruction_text="Apply the transformation."),
    # Complex Numbers
    _a2("Complex Numbers", "a2_complex_numbers_operations", "Operations", generator="complex_operations", instruction_latex="\\text{Evaluate.}", instruction_text="Evaluate."),
    _a2("Complex Numbers", "a2_complex_numbers_graphing", "Graphing", generator="complex_graph", instruction_latex="\\text{Graph the number.}", instruction_text="Graph the number."),
    _a2("Complex Numbers", "a2_complex_numbers_absolute_value", "Absolute value", generator="complex_absolute_value", instruction_text="Find the absolute value."),
    _a2("Complex Numbers", "a2_complex_numbers_rationalizing_denominators", "Rationalizing denominators", instruction_text="Rationalize the denominator.", generator="complex_rationalize_denominator"),
    # Quadratic Functions and Inequalities
    _a2("Quadratic Functions and Inequalities", "a2_quadratic_functions_and_inequalities_graphing_quadratic_functions", "Graphing quadratic functions", generator="quadratic_graph_vertex", instruction_latex="\\text{Graph the following functions.}", instruction_text="Graph the following functions."),
    _a2("Quadratic Functions and Inequalities", "a2_quadratic_functions_and_inequalities_graphing_quadratic_inequalities", "Graphing quadratic inequalities", generator="quadratic_graph_inequality", instruction_latex="\\text{Graph the following inequalities.}", instruction_text="Graph the following inequalities."),
    _a2("Quadratic Functions and Inequalities", "a2_quadratic_functions_and_inequalities_solving_equations_by_graphing", "Solving equations by graphing", generator="solve_polynomial_by_graphing", instruction_latex="\\text{Solve by graphing.}", instruction_text="Solve by graphing."),
    _a2("Quadratic Functions and Inequalities", "a2_quadratic_functions_and_inequalities_factoring_quadratic_expressions", "Factoring quadratic expressions", generator="quadratic_factoring", instruction_latex="\\text{Factor.}", instruction_text="Factor."),
    _a2("Quadratic Functions and Inequalities", "a2_quadratic_functions_and_inequalities_factoring_special_case_quadratic_expressions", "Factoring special case quadratic expressions", generator="polynomial_factoring_special_cases", instruction_latex="\\text{Factor.}", instruction_text="Factor."),
    _a2("Quadratic Functions and Inequalities", "a2_quadratic_functions_and_inequalities_solving_equations_by_taking_square_roots", "Solving equations by taking square roots", generator="quadratic_square_roots", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    _a2("Quadratic Functions and Inequalities", "a2_quadratic_functions_and_inequalities_solving_equations_by_factoring", "Solving equations by factoring", generator="quadratic_factoring_equations", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    _a2("Quadratic Functions and Inequalities", "a2_quadratic_functions_and_inequalities_completing_the_square", "Completing the square", generator="quadratic_completing_square_constant", instruction_text="Complete the square."),
    _a2("Quadratic Functions and Inequalities", "a2_quadratic_functions_and_inequalities_solving_equations_by_completing_the_square", "Solving equations by completing the square", generator="quadratic_completing_square_solve", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    _a2("Quadratic Functions and Inequalities", "a2_quadratic_functions_and_inequalities_solving_equations_with_the_quadratic_formula", "Solving equations with the Quadratic Formula", generator="quadratic_formula", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    _a2("Quadratic Functions and Inequalities", "a2_quadratic_functions_and_inequalities_the_discriminant", "The discriminant", generator="quadratic_discriminant", instruction_text="Find the discriminant."),
    # Polynomial Functions
    _a2("Polynomial Functions", "a2_polynomial_functions_naming", "Naming", generator="polynomial_naming", instruction_text="Name the polynomial."),
    _a2(
        "Polynomial Functions",
        "a2_polynomial_functions_simplifying",
        "Simplifying",
        generator="simplify_polynomials",
        instruction_latex=r"\text{Simplify.}",
        instruction_text="Simplify.",
    ),
    _a2("Polynomial Functions", "a2_polynomial_functions_adding_and_subtracting", "Adding and subtracting", generator="polynomial_add_subtract", instruction_latex="\\text{Simplify.}", instruction_text="Simplify."),
    _a2("Polynomial Functions", "a2_polynomial_functions_multiplying", "Multiplying", generator="polynomial_multiply", instruction_text="Multiply."),
    _a2("Polynomial Functions", "a2_polynomial_functions_multiplying_special_cases", "Multiplying special cases", generator="polynomial_multiply_special", instruction_text="Multiply."),
    _a2("Polynomial Functions", "a2_polynomial_functions_the_binomial_theorem", "The Binomial Theorem", generator="binomial_theorem", instruction_text="Expand."),
    _a2("Polynomial Functions", "a2_polynomial_functions_dividing", "Dividing", generator="polynomial_long_division", instruction_text="Divide."),
    _a2("Polynomial Functions", "a2_polynomial_functions_factoring_by_grouping", "Factoring by grouping", generator="polynomial_factoring_grouping", instruction_latex="\\text{Factor.}", instruction_text="Factor."),
    _a2("Polynomial Functions", "a2_polynomial_functions_factoring_sum_difference_of_cubes", "Factoring a sum/difference of cubes", generator="a2_polynomial_functions_factoring_sum_difference_of_cubes", instruction_latex="\\text{Factor.}", instruction_text="Factor."),
    _a2("Polynomial Functions", "a2_polynomial_functions_factoring_quadratic_form", "Factoring quadratic form", generator="a2_polynomial_functions_factoring_quadratic_form", instruction_latex="\\text{Factor.}", instruction_text="Factor."),
    _a2("Polynomial Functions", "a2_polynomial_functions_factoring_all_techniques", "Factoring all techniques", generator="a2_polynomial_functions_factoring_all_techniques", instruction_latex="\\text{Factor.}", instruction_text="Factor."),
    _a2("Polynomial Functions", "a2_polynomial_functions_the_remainder_theorem", "The Remainder Theorem", generator="remainder_theorem", instruction_text="Find the remainder."),
    _a2("Polynomial Functions", "a2_polynomial_functions_writing_functions", "Writing functions", generator="polynomial_writing", instruction_text="Write the function."),
    _a2("Polynomial Functions", "a2_polynomial_functions_conjugate_roots_and_factoring", "Conjugate roots & factoring", generator="polynomial_factoring_special_cases", instruction_latex="\\text{Factor.}", instruction_text="Factor."),
    _a2("Polynomial Functions", "a2_polynomial_functions_conjugate_roots_and_writing_functions", "Conjugate roots & writing functions", generator="polynomial_conjugate_writing", instruction_text="Write the function."),
    _a2("Polynomial Functions", "a2_polynomial_functions_descartes_rule_of_signs", "Descartes' Rule of Signs", generator="descartes_rule_of_signs", instruction_text="Apply the rule."),
    _a2("Polynomial Functions", "a2_polynomial_functions_rational_zero_root_theorem", "Rational Zero/Root Theorem", generator="rational_zero_root_theorem", instruction_text="Find the zeros."),
    _a2("Polynomial Functions", "a2_polynomial_functions_fundamental_theorem_of_algebra", "Fundamental Theorem of Algebra", generator="fundamental_theorem_algebra", instruction_text="Find the zeros."),
    _a2("Polynomial Functions", "a2_polynomial_functions_solving_polynomial_equations", "Solving polynomial equations", generator="quadratic_factoring_equations", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    _a2("Polynomial Functions", "a2_polynomial_functions_end_behavior_and_general_graph_shape", "End behavior and general graph shape", generator="polynomial_end_behavior", instruction_text="Describe the end behavior."),
    _a2("Polynomial Functions", "a2_polynomial_functions_graphing", "Graphing", generator="graph_quadratic", instruction_latex="\\text{Graph the following functions.}", instruction_text="Graph the following functions."),
    # General Functions
    _a2("General Functions", "a2_general_functions_evaluating", "Evaluating", generator="function_evaluate", instruction_latex="\\text{Evaluate.}", instruction_text="Evaluate."),
    _a2("General Functions", "a2_general_functions_operations", "Operations", generator="function_operations", instruction_latex="\\text{Evaluate.}", instruction_text="Evaluate."),
    _a2("General Functions", "a2_general_functions_inverses", "Inverses", generator="inverse_function_basic", instruction_text="Find the inverse."),
    # Radical Functions and Rational Exponents
    _a2("Radical Functions and Rational Exponents", "a2_radical_functions_and_rational_exponents_simplifying_radicals", "Simplifying radicals", generator="radical_simplification", instruction_latex="\\text{Simplify.}", instruction_text="Simplify."),
    _a2("Radical Functions and Rational Exponents", "a2_radical_functions_and_rational_exponents_adding_and_subtracting_radical_expressions", "Adding and subtracting radical expressions", generator="radical_add_subtract", instruction_latex="\\text{Simplify.}", instruction_text="Simplify."),
    _a2("Radical Functions and Rational Exponents", "a2_radical_functions_and_rational_exponents_multiplying_radical_expressions", "Multiplying radical expressions", generator="radical_multiply", instruction_latex="\\text{Simplify.}", instruction_text="Simplify."),
    _a2("Radical Functions and Rational Exponents", "a2_radical_functions_and_rational_exponents_dividing_radical_expressions", "Dividing radical expressions", generator="radical_divide", instruction_latex="\\text{Simplify.}", instruction_text="Simplify."),
    _a2("Radical Functions and Rational Exponents", "a2_radical_functions_and_rational_exponents_connecting_radical_expressions_and_rational_exponents", "Connecting radical expressions and rational exponents", generator="properties_of_exponents", instruction_text="Rewrite the expression."),
    _a2("Radical Functions and Rational Exponents", "a2_radical_functions_and_rational_exponents_evaluating_rational_exponent_expressions", "Evaluating rational exponent expressions", generator="properties_of_exponents", instruction_latex="\\text{Evaluate.}", instruction_text="Evaluate."),
    _a2("Radical Functions and Rational Exponents", "a2_radical_functions_and_rational_exponents_the_properties_of_exponents", "The properties of exponents", generator="properties_of_exponents", instruction_latex="\\text{Simplify.}", instruction_text="Simplify."),
    _a2("Radical Functions and Rational Exponents", "a2_radical_functions_and_rational_exponents_radical_equations", "Radical equations", generator="radical_equations", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    _a2("Radical Functions and Rational Exponents", "a2_radical_functions_and_rational_exponents_rational_exponent_equations", "Rational exponent equations", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x.", generator="radical_equations"),
    _a2("Radical Functions and Rational Exponents", "a2_radical_functions_and_rational_exponents_graphing_radical_equations", "Graphing radical equations", generator="graph_radical", instruction_latex="\\text{Graph the following equations.}", instruction_text="Graph the following equations."),
    _a2("Radical Functions and Rational Exponents", "a2_radical_functions_and_rational_exponents_domain_and_range_of_radical_functions", "Domain and range of radical functions", generator="radical_domain_range", instruction_text="Find the domain and range."),
    # Conic Sections
    _a2("Conic Sections", "a2_conic_sections_parabolas_graphing_and_properties", "Parabolas graphing & properties", generator="quadratic_graph_vertex", instruction_latex="\\text{Graph or identify properties.}", instruction_text="Graph or identify properties."),
    _a2("Conic Sections", "a2_conic_sections_parabolas_writing_equations", "Parabolas writing equations", generator="quadratic_vertex_form_write", instruction_text="Write the equation."),
    _a2("Conic Sections", "a2_conic_sections_circles_graphing_and_properties", "Circles graphing & properties", generator="conic_sections", instruction_latex="\\text{Graph or identify properties.}", instruction_text="Graph or identify properties."),
    _a2("Conic Sections", "a2_conic_sections_circles_writing_equations", "Circles writing equations", generator="conic_sections", instruction_text="Write the equation."),
    _a2("Conic Sections", "a2_conic_sections_ellipses_graphing_and_properties", "Ellipses graphing & properties", generator="conic_sections", instruction_latex="\\text{Graph or identify properties.}", instruction_text="Graph or identify properties."),
    _a2("Conic Sections", "a2_conic_sections_ellipses_writing_equations", "Ellipses writing equations", generator="conic_sections", instruction_text="Write the equation."),
    _a2("Conic Sections", "a2_conic_sections_hyperbolas_graphing_and_properties", "Hyperbolas graphing & properties", generator="conic_sections", instruction_latex="\\text{Graph or identify properties.}", instruction_text="Graph or identify properties."),
    _a2("Conic Sections", "a2_conic_sections_hyperbolas_writing_equations", "Hyperbolas writing equations", generator="conic_sections", instruction_text="Write the equation."),
    _a2("Conic Sections", "a2_conic_sections_classifying", "Classifying", generator="conic_sections", instruction_text="Classify the conic."),
    _a2("Conic Sections", "a2_conic_sections_systems_of_quadratic_equations", "Systems of quadratic equations", generator="quadratic_system", instruction_text="Solve the system."),
    # Rational Expressions
    _a2("Rational Expressions", "a2_rational_expressions_graphing", "Graphing rational functions", generator="graph_rational", instruction_latex="\\text{Graph the following functions.}", instruction_text="Graph the following functions."),
    # Hand-written: rational_simplification, rational_expression_simplification (see verify_curriculum_types.HAND_WRITTEN)
    _a2("Rational Expressions", "a2_rational_expressions_simplifying", "Simplifying rational expressions", generator="rational_simplification", instruction_latex="\\text{Simplify.}", instruction_text="Simplify."),
    _a2("Rational Expressions", "a2_rational_expressions_multiplying_and_dividing", "Multiplying and dividing rational expressions", generator="rational_expression_multiply_divide", instruction_latex="\\text{Simplify.}", instruction_text="Simplify."),
    _a2("Rational Expressions", "a2_rational_expressions_adding_and_subtracting", "Adding and subtracting rational expressions", generator="rational_expression_simplification", instruction_latex="\\text{Combine and simplify.}", instruction_text="Combine and simplify."),
    _a2("Rational Expressions", "a2_rational_expressions_complex_fractions", "Complex fractions", generator="complex_fractions", instruction_latex="\\text{Simplify.}", instruction_text="Simplify."),
    _a2("Rational Expressions", "a2_rational_expressions_equations", "Rational equations", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x.", generator="rational_equations"),
    # Exponential and Logarithmic Expressions
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_graphing_exponential_functions", "Graphing exponential functions", generator="graph_exponential", instruction_latex="\\text{Graph the following functions.}", instruction_text="Graph the following functions."),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_exponential_equations_not_requiring_logarithms", "Exponential equations not requiring logarithms", generator="exponential_equation_simple", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_exponents_and_logarithms", "Exponents and logarithms", instruction_text="Rewrite the expression.", generator="log_evaluate"),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_evaluating_logarithms", "Evaluating logarithms", generator="log_evaluate", instruction_latex="\\text{Evaluate.}", instruction_text="Evaluate."),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_logarithms_and_exponents_as_inverses", "Logarithms and exponents as inverses", instruction_text="Rewrite the expression.", generator="log_evaluate"),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_properties_of_logarithms", "Properties of logarithms", generator="log_change_of_base", instruction_latex="\\text{Simplify.}", instruction_text="Simplify."),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_writing_logs_in_terms_of_others", "Writing logs in terms of others", instruction_text="Rewrite the logarithm.", generator="log_change_of_base"),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_exponential_equations_requiring_logarithms", "Exponential equations requiring logarithms", generator="exponential_equation_with_log", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_inverses_of_exponential_and_logarithmic_functions", "Inverses of exponential and logarithmic functions", generator="inverse_exponential_logarithmic", instruction_text="Find the inverse."),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_logarithmic_equations_simple", "Logarithmic equations, simple", generator="log_equation_simple", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_logarithmic_equations_hard", "Logarithmic equations, hard", generator="log_equation_simple", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_graphing_logarithmic_functions", "Graphing logarithmic functions", generator="graph_logarithmic", instruction_latex="\\text{Graph the following functions.}", instruction_text="Graph the following functions."),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_discrete_exponential_growth_and_decay_word_problems", "Discrete exponential growth and decay word problems", generator="exponential_growth_decay", instruction_latex="\\text{Solve the problem.}", instruction_text="Solve the problem.", count_default=5),
    _a2("Exponential and Logarithmic Expressions", "a2_exponential_and_logarithmic_expressions_continuous_exponential_growth_and_decay_word_problems", "Continuous exponential growth and decay word problems", generator="exponential_growth_decay", instruction_latex="\\text{Solve the problem.}", instruction_text="Solve the problem.", count_default=5),
    # Sequences and Series
    _a2("Sequences and Series", "a2_sequences_and_series_general_sequences", "General sequences", instruction_text="Find the term.", generator="sequence_arithmetic_nth_term"),
    _a2("Sequences and Series", "a2_sequences_and_series_arithmetic_sequences", "Arithmetic sequences", generator="sequence_arithmetic_nth_term", instruction_text="Find the term."),
    _a2("Sequences and Series", "a2_sequences_and_series_geometric_sequences", "Geometric sequences", generator="sequence_geometric_nth_term", instruction_text="Find the term."),
    _a2("Sequences and Series", "a2_sequences_and_series_arithmetic_and_geometric_mean", "Arithmetic and geometric mean", generator="sequence_arithmetic_geometric_mean", instruction_text="Find the mean."),
    _a2("Sequences and Series", "a2_sequences_and_series_general_series", "General series", instruction_text="Evaluate the series.", generator="sequence_arithmetic_series"),
    _a2("Sequences and Series", "a2_sequences_and_series_arithmetic_series", "Arithmetic series", generator="sequence_arithmetic_series", instruction_text="Evaluate the series."),
    _a2("Sequences and Series", "a2_sequences_and_series_geometric_series", "Geometric series", generator="sequence_geometric_series", instruction_text="Evaluate the series."),
    # Trigonometry
    _a2("Trigonometry", "a2_trigonometry_angles_and_angle_measure", "Angles and angle measure", generator="angle_measure", instruction_text="Find the measure."),
    _a2("Trigonometry", "a2_trigonometry_radians_and_degrees", "Radians and degrees", generator="trig_unit_circle", instruction_text="Convert."),
    _a2("Trigonometry", "a2_trigonometry_degrees_and_degrees_minutes_seconds", "Degrees and degrees-minutes-seconds", generator="degrees_minutes_seconds", instruction_text="Convert."),
    _a2("Trigonometry", "a2_trigonometry_coterminal_angles", "Coterminal angles", generator="trig_unit_circle", instruction_text="Find a coterminal angle."),
    _a2("Trigonometry", "a2_trigonometry_arc_length_and_sector_area", "Arc length and sector area", generator="geo_arc_sector", instruction_text="Find the measure."),
    _a2("Trigonometry", "a2_trigonometry_right_triangle_trig_finding_ratios", "Right triangle trig, finding ratios", generator="geo_right_triangle_trig_ratio", instruction_text="Find the ratio."),
    _a2("Trigonometry", "a2_trigonometry_right_triangle_trig_finding_angle_measures", "Right triangle trig, finding angle measures", generator="geo_right_triangle_trig_angle", instruction_text="Find the angle measure."),
    _a2("Trigonometry", "a2_trigonometry_right_triangle_trig_angles_and_sides", "Right triangle trig, angles and sides", generator="geo_right_triangle_trig", instruction_text="Find the missing value."),
    _a2("Trigonometry", "a2_trigonometry_trig_functions_of_any_angle", "Trig functions of any angle", generator="trig_evaluate", instruction_latex="\\text{Evaluate.}", instruction_text="Evaluate."),
    _a2("Trigonometry", "a2_trigonometry_the_law_of_sines", "Law of Sines", generator="law_of_sines", instruction_text="Solve the triangle."),
    _a2("Trigonometry", "a2_trigonometry_the_law_of_cosines", "Law of Cosines", generator="law_of_cosines", instruction_text="Solve the triangle."),
    _a2("Trigonometry", "a2_trigonometry_area_and_laws_of_sines_and_cosines", "Area and Laws", generator="law_of_sines", instruction_text="Find the area."),
    _a2("Trigonometry", "a2_trigonometry_graphing_trig_functions", "Graphing trig functions", generator="graphing_trig_functions", instruction_latex="\\text{Graph the following functions.}", instruction_text="Graph the following functions."),
    _a2("Trigonometry", "a2_trigonometry_angle_sum_difference_identities", "Angle sum/difference identities", generator="trig_sum_difference", instruction_latex="\\text{Simplify.}", instruction_text="Simplify."),
    _a2("Trigonometry", "a2_trigonometry_double_angle_half_angle_identities", "Double-angle/half-angle identities", generator="trig_multiple_angle", instruction_latex="\\text{Simplify.}", instruction_text="Simplify."),
    _a2("Trigonometry", "a2_trigonometry_equations", "Equations", generator="simple_trig_equations", instruction_latex="\\text{Solve for } x.", instruction_text="Solve for x."),
    # Probability and Statistics
    _a2("Probability and Statistics", "a2_probability_and_statistics_sample_spaces_and_the_fundamental_counting_principle", "Sample spaces and the Fundamental Counting Principle", generator="stats_counting_principle", instruction_text="Find the number of outcomes."),
    _a2("Probability and Statistics", "a2_probability_and_statistics_probability_of_independent_and_dependent_events_word_problems", "Probability of independent and dependent events, word problems", generator="stats_probability_compound_independent", instruction_latex="\\text{Solve the problem.}", instruction_text="Solve the problem.", count_default=5),
    _a2("Probability and Statistics", "a2_probability_and_statistics_probability_of_independent_and_dependent_events", "Probability of independent and dependent events", generator="stats_probability_compound_independent", instruction_text="Find the probability."),
    _a2("Probability and Statistics", "a2_probability_and_statistics_probability_of_mutually_exclusive_events_word_problems", "Probability of mutually exclusive events, word problems", generator="stats_probability_mutually_exclusive", instruction_latex="\\text{Solve the problem.}", instruction_text="Solve the problem.", count_default=5),
    _a2("Probability and Statistics", "a2_probability_and_statistics_probability_of_mutually_exclusive_events", "Probability of mutually exclusive events", generator="stats_probability_mutually_exclusive", instruction_text="Find the probability."),
    _a2("Probability and Statistics", "a2_probability_and_statistics_permutations", "Permutations", generator="stats_permutations", instruction_text="Find the number of permutations."),
    _a2("Probability and Statistics", "a2_probability_and_statistics_combinations", "Combinations", generator="stats_combinations", instruction_text="Find the number of combinations."),
    _a2("Probability and Statistics", "a2_probability_and_statistics_permutations_vs_combinations", "Permutations vs combinations", generator="stats_permutations_vs_combinations", instruction_text="Determine whether to use permutations or combinations."),
    _a2("Probability and Statistics", "a2_probability_and_statistics_probability_with_permutations_and_combinations", "Probability with permutations and combinations", generator="stats_permutations_vs_combinations", instruction_text="Find the probability."),
)
