COURSE_ID = "precalculus"

CATEGORY_ORDER: tuple[str, ...] = (
    'Precalculus — Functions',
    'Precalculus — Power, Polynomial, and Rational Functions',
    'Precalculus — Exponential and Logarithmic Expressions',
    'Precalculus — Trigonometry',
    'Precalculus — Parametric Equations',
    'Precalculus — Polar Coordinates',
    'Precalculus — Vectors',
    'Precalculus — Three-Dimensional Vectors',
    'Precalculus — Matrices and Systems',
    'Precalculus — Conic Sections',
    'Precalculus — Discrete Mathematics',
    'Precalculus — Sequences and Series',
    'Precalculus — Introduction to Calculus',
)

from .base import TypeCatalogEntry



def _pc(
    chapter: str,
    id: str,
    name: str,
    *,
    instruction_latex: str = "",
    instruction_text: str = "",
    count_default: int = 10,
    generator: str = "scaffold",
) -> TypeCatalogEntry:
    return TypeCatalogEntry(
        id=id,
        name=name,
        category=f"Precalculus — {chapter}",
        generator=generator,
        description=f"Practice {name.lower()}.",
        instruction_latex=instruction_latex or "\\text{Solve.}",
        instruction_text=instruction_text or "Solve.",
        count_default=count_default,
    )


CATALOG: tuple[TypeCatalogEntry, ...] = (
    # Functions
    _pc("Functions", "pc_continuity", "Continuity"),
    _pc(
        "Functions",
        "pc_extrema_intervals_of_increase_and_decrease",
        "Extrema, intervals of increase and decrease",
        instruction_text="Find the extrema and intervals.",
    ),
    _pc("Functions", "pc_power_functions", "Power functions", instruction_text="Graph or evaluate."),
    _pc(
        "Functions",
        "pc_average_rates_of_change",
        "Average rates of change",
        instruction_text="Find the average rate of change.",
    ),
    _pc(
        "Functions",
        "pc_transformations_of_graphs",
        "Transformations of graphs",
        instruction_latex="\\text{Graph the function.}",
        instruction_text="Graph the function.",
    ),
    _pc("Functions", "pc_piecewise_functions", "Piecewise functions", instruction_text="Evaluate or graph."),
    _pc("Functions", "pc_functions_operations", "Operations", instruction_text="Evaluate."),
    _pc("Functions", "pc_inverses", "Inverses", instruction_text="Find the inverse."),
    # Power, Polynomial, and Rational Functions
    _pc(
        "Power, Polynomial, and Rational Functions",
        "pc_polynomial_graphs_real_zeros_and_end_behavior",
        "Graphs, real zeros, and end behavior of polynomial functions",
        instruction_text="Analyze the polynomial.",
    ),
    _pc(
        "Power, Polynomial, and Rational Functions",
        "pc_dividing_polynomial_functions",
        "Dividing polynomial functions",
        instruction_latex="\\text{Divide.}",
        instruction_text="Divide.",
    ),
    _pc(
        "Power, Polynomial, and Rational Functions",
        "pc_remainder_theorem_and_bounds_of_real_zeros",
        "The Remainder Theorem and bounds of real zeros",
        instruction_text="Apply the Remainder Theorem.",
    ),
    _pc(
        "Power, Polynomial, and Rational Functions",
        "pc_writing_polynomial_functions_and_conjugate_roots",
        "Writing polynomial functions and conjugate roots",
        instruction_text="Write the polynomial function.",
    ),
    _pc(
        "Power, Polynomial, and Rational Functions",
        "pc_complex_zeros_and_fundamental_theorem_of_algebra",
        "Complex zeros and The Fundamental Theorem of Algebra",
        instruction_text="Find the zeros.",
    ),
    _pc(
        "Power, Polynomial, and Rational Functions",
        "pc_graphs_of_rational_functions",
        "Graphs of rational functions",
        instruction_latex="\\text{Graph the function.}",
        instruction_text="Graph the function.",
    ),
    _pc(
        "Power, Polynomial, and Rational Functions",
        "pc_rational_equations",
        "Rational equations",
        instruction_latex="\\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    _pc(
        "Power, Polynomial, and Rational Functions",
        "pc_polynomial_inequalities",
        "Polynomial inequalities",
        instruction_latex="\\text{Solve the inequality.}",
        instruction_text="Solve the inequality.",
    ),
    _pc(
        "Power, Polynomial, and Rational Functions",
        "pc_rational_inequalities",
        "Rational inequalities",
        instruction_latex="\\text{Solve the inequality.}",
        instruction_text="Solve the inequality.",
    ),
    # Exponential and Logarithmic Expressions
    _pc(
        "Exponential and Logarithmic Expressions",
        "pc_graphing_exponential_functions",
        "Graphing exponential functions",
        instruction_latex="\\text{Graph the function.}",
        instruction_text="Graph the function.",
    ),
    _pc(
        "Exponential and Logarithmic Expressions",
        "pc_exponential_equations_not_requiring_logarithms",
        "Exponential equations not requiring logarithms",
        instruction_latex="\\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    _pc(
        "Exponential and Logarithmic Expressions",
        "pc_exponents_and_logarithms",
        "Exponents and logarithms",
        instruction_text="Evaluate or simplify.",
    ),
    _pc(
        "Exponential and Logarithmic Expressions",
        "pc_evaluating_logarithms",
        "Evaluating logarithms",
        instruction_text="Evaluate.",
    ),
    _pc(
        "Exponential and Logarithmic Expressions",
        "pc_logarithms_and_exponents_as_inverses",
        "Logarithms and exponents as inverses",
        instruction_text="Rewrite using inverses.",
    ),
    _pc(
        "Exponential and Logarithmic Expressions",
        "pc_properties_of_logarithms",
        "Properties of logarithms",
        instruction_latex="\\text{Simplify.}",
        instruction_text="Simplify.",
    ),
    _pc(
        "Exponential and Logarithmic Expressions",
        "pc_writing_logs_in_terms_of_others",
        "Writing logs in terms of others",
        instruction_text="Rewrite the logarithm.",
    ),
    _pc(
        "Exponential and Logarithmic Expressions",
        "pc_exponential_equations_requiring_logarithms",
        "Exponential equations requiring logarithms",
        instruction_latex="\\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    _pc(
        "Exponential and Logarithmic Expressions",
        "pc_logarithmic_equations_simple",
        "Logarithmic equations, simple",
        instruction_latex="\\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    _pc(
        "Exponential and Logarithmic Expressions",
        "pc_logarithmic_equations_hard",
        "Logarithmic equations, hard",
        instruction_latex="\\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    _pc(
        "Exponential and Logarithmic Expressions",
        "pc_graphing_logarithmic_functions",
        "Graphing logarithmic functions",
        instruction_latex="\\text{Graph the function.}",
        instruction_text="Graph the function.",
    ),
    _pc(
        "Exponential and Logarithmic Expressions",
        "pc_compound_interest",
        "Compound interest",
        instruction_latex="\\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    # Trigonometry
    _pc(
        "Trigonometry",
        "pc_angles_and_angle_measure",
        "Angles and angle measure",
        instruction_text="Find the measure.",
    ),
    _pc(
        "Trigonometry",
        "pc_radians_and_degrees",
        "Radians and degrees",
        instruction_text="Convert between radians and degrees.",
    ),
    _pc(
        "Trigonometry",
        "pc_right_triangle_trig_finding_ratios",
        "Right triangle trig, finding ratios",
        instruction_text="Find the trigonometric ratio.",
    ),
    _pc(
        "Trigonometry",
        "pc_right_triangle_trig_finding_angles_and_sides",
        "Right triangle trig, finding angles and sides",
        instruction_text="Find the missing measure.",
    ),
    _pc(
        "Trigonometry",
        "pc_trig_functions_of_any_angle",
        "Trig functions of any angle",
        instruction_text="Evaluate the trigonometric function.",
    ),
    _pc(
        "Trigonometry",
        "pc_graphing_trig_functions",
        "Graphing trig functions",
        instruction_latex="\\text{Graph the function.}",
        instruction_text="Graph the function.",
    ),
    _pc(
        "Trigonometry",
        "pc_simple_trig_equations",
        "Simple trig equations",
        instruction_latex="\\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    _pc(
        "Trigonometry",
        "pc_inverse_trig_functions",
        "Inverse trig functions",
        instruction_text="Evaluate the inverse trigonometric function.",
    ),
    _pc(
        "Trigonometry",
        "pc_fundamental_identities",
        "Fundamental identities",
        instruction_latex="\\text{Simplify.}",
        instruction_text="Simplify.",
    ),
    _pc(
        "Trigonometry",
        "pc_equations_with_factoring_and_fundamental_identities",
        "Equations with factoring and fundamental identities",
        instruction_latex="\\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    _pc(
        "Trigonometry",
        "pc_sum_and_difference_identities",
        "Sum and Difference Identities",
        instruction_latex="\\text{Simplify.}",
        instruction_text="Simplify.",
    ),
    _pc(
        "Trigonometry",
        "pc_multiple_angle_identities",
        "Multiple-Angle Identities",
        instruction_latex="\\text{Simplify.}",
        instruction_text="Simplify.",
    ),
    _pc(
        "Trigonometry",
        "pc_product_to_sum_identities",
        "Product-to-Sum Identities",
        instruction_latex="\\text{Simplify.}",
        instruction_text="Simplify.",
    ),
    _pc(
        "Trigonometry",
        "pc_equations_and_multiple_angle_identities",
        "Equations and Multiple-Angle Identities",
        instruction_latex="\\text{Solve for } x.",
        instruction_text="Solve for x.",
    ),
    _pc(
        "Trigonometry",
        "pc_law_of_sines",
        "The Law of Sines",
        instruction_text="Find the missing measure.",
    ),
    _pc(
        "Trigonometry",
        "pc_law_of_cosines",
        "The Law of Cosines",
        instruction_text="Find the missing measure.",
    ),
    _pc(
        "Trigonometry",
        "pc_area_and_laws_of_sines_and_cosines",
        "Area and Laws of Sines and Cosines",
        instruction_text="Find the area or missing measure.",
    ),
    # Parametric Equations
    _pc(
        "Parametric Equations",
        "pc_parametric_equations",
        "Parametric equations",
        instruction_text="Solve or graph.",
    ),
    _pc(
        "Parametric Equations",
        "pc_projectile_motion",
        "Projectile motion",
        instruction_latex="\\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    # Polar Coordinates
    _pc(
        "Polar Coordinates",
        "pc_polar_coordinates",
        "Polar coordinates",
        instruction_text="Convert or plot.",
    ),
    _pc(
        "Polar Coordinates",
        "pc_graphs_of_polar_equations",
        "Graphs of polar equations",
        instruction_latex="\\text{Graph the equation.}",
        instruction_text="Graph the equation.",
    ),
    _pc(
        "Polar Coordinates",
        "pc_polar_and_rectangular_forms_of_equations",
        "Polar and rectangular forms of equations",
        instruction_text="Convert the equation.",
    ),
    _pc(
        "Polar Coordinates",
        "pc_polar_forms_of_conic_sections",
        "Polar forms of conic sections",
        instruction_text="Identify or write the equation.",
    ),
    _pc(
        "Polar Coordinates",
        "pc_complex_numbers_in_polar_form",
        "Complex numbers in polar form",
        instruction_text="Convert or evaluate.",
    ),
    # Vectors
    _pc("Vectors", "pc_vectors_basics", "Basics", instruction_text="Evaluate."),
    _pc("Vectors", "pc_vectors_diagrams", "Diagrams", instruction_text="Draw or interpret the diagram."),
    _pc("Vectors", "pc_vectors_operations", "Operations", instruction_text="Evaluate."),
    _pc("Vectors", "pc_dot_products", "Dot products", instruction_text="Find the dot product."),
    # Three-Dimensional Vectors
    _pc(
        "Three-Dimensional Vectors",
        "pc_3d_points_in_three_dimensions",
        "Points in three dimensions",
        instruction_text="Find the distance or coordinates.",
    ),
    _pc("Three-Dimensional Vectors", "pc_3d_vectors_basics", "Basics", instruction_text="Evaluate."),
    _pc("Three-Dimensional Vectors", "pc_3d_vectors_operations", "Operations", instruction_text="Evaluate."),
    _pc(
        "Three-Dimensional Vectors",
        "pc_cross_products",
        "Cross products",
        instruction_text="Find the cross product.",
    ),
    # Matrices and Systems
    _pc(
        "Matrices and Systems",
        "pc_multivariable_linear_systems_and_row_operations",
        "Multivariable linear systems and row operations",
        instruction_text="Solve the system.",
    ),
    _pc(
        "Matrices and Systems",
        "pc_partial_fraction_decomposition",
        "Partial fraction decomposition",
        instruction_text="Decompose the expression.",
    ),
    # Conic Sections
    _pc(
        "Conic Sections",
        "pc_parabolas_graphing_and_properties",
        "Parabolas, graphing and properties",
        instruction_latex="\\text{Graph the parabola.}",
        instruction_text="Graph the parabola.",
    ),
    _pc(
        "Conic Sections",
        "pc_parabolas_writing_equations",
        "Parabolas, writing equations",
        instruction_text="Write the equation of the parabola.",
    ),
    _pc(
        "Conic Sections",
        "pc_circles_graphing_and_properties",
        "Circles, graphing and properties",
        instruction_latex="\\text{Graph the circle.}",
        instruction_text="Graph the circle.",
    ),
    _pc(
        "Conic Sections",
        "pc_circles_writing_equations",
        "Circles, writing equations",
        instruction_text="Write the equation of the circle.",
    ),
    _pc(
        "Conic Sections",
        "pc_ellipses_graphing_and_properties",
        "Ellipses, graphing and properties",
        instruction_latex="\\text{Graph the ellipse.}",
        instruction_text="Graph the ellipse.",
    ),
    _pc(
        "Conic Sections",
        "pc_ellipses_writing_equations",
        "Ellipses, writing equations",
        instruction_text="Write the equation of the ellipse.",
    ),
    _pc(
        "Conic Sections",
        "pc_hyperbolas_graphing_and_properties",
        "Hyperbolas, graphing and properties",
        instruction_latex="\\text{Graph the hyperbola.}",
        instruction_text="Graph the hyperbola.",
    ),
    _pc(
        "Conic Sections",
        "pc_hyperbolas_writing_equations",
        "Hyperbolas, writing equations",
        instruction_text="Write the equation of the hyperbola.",
    ),
    _pc(
        "Conic Sections",
        "pc_rotations_of_conic_sections",
        "Rotations of conic sections",
        instruction_text="Identify or write the equation.",
    ),
    # Discrete Mathematics
    _pc(
        "Discrete Mathematics",
        "pc_sample_spaces_and_fundamental_counting_principle",
        "Sample spaces and Fundamental Counting Principle",
        instruction_text="Find the number of outcomes.",
    ),
    _pc(
        "Discrete Mathematics",
        "pc_permutations_vs_combinations",
        "Permutations vs combinations",
        instruction_text="Determine whether to use permutations or combinations.",
    ),
    _pc(
        "Discrete Mathematics",
        "pc_binomial_theorem",
        "The Binomial Theorem",
        instruction_text="Expand using the Binomial Theorem.",
    ),
    _pc(
        "Discrete Mathematics",
        "pc_mathematical_induction",
        "Mathematical induction",
        instruction_text="Prove by mathematical induction.",
    ),
    _pc(
        "Discrete Mathematics",
        "pc_probability_independent_dependent_events_word_problems",
        "Probability: Independent/dependent events, word problems",
        instruction_latex="\\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    _pc(
        "Discrete Mathematics",
        "pc_probability_independent_dependent_events",
        "Probability: Independent/dependent events",
        instruction_text="Find the probability.",
    ),
    _pc(
        "Discrete Mathematics",
        "pc_probability_mutually_exclusive_word_problems",
        "Probability: Mutually exclusive, word problems",
        instruction_latex="\\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    _pc(
        "Discrete Mathematics",
        "pc_probability_mutually_exclusive",
        "Probability: Mutually exclusive",
        instruction_text="Find the probability.",
    ),
    _pc(
        "Discrete Mathematics",
        "pc_probability_with_permutations_and_combinations",
        "Probability: With permutations and combinations",
        instruction_text="Find the probability.",
    ),
    # Sequences and Series
    _pc("Sequences and Series", "pc_power_series", "Power series", instruction_text="Evaluate the series."),
    # Introduction to Calculus
    _pc(
        "Introduction to Calculus",
        "pc_limits_by_direct_evaluation",
        "Limits by direct evaluation",
        instruction_text="Evaluate the limit.",
    ),
    _pc(
        "Introduction to Calculus",
        "pc_limits_at_kinks_and_jumps",
        "Limits at kinks and jumps",
        instruction_text="Evaluate the limit.",
    ),
    _pc(
        "Introduction to Calculus",
        "pc_limits_at_removable_discontinuities",
        "Limits at removable discontinuities",
        instruction_text="Evaluate the limit.",
    ),
    _pc(
        "Introduction to Calculus",
        "pc_limits_at_essential_discontinuities",
        "Limits at essential discontinuities",
        instruction_text="Evaluate the limit.",
    ),
    _pc(
        "Introduction to Calculus",
        "pc_limits_at_infinity",
        "Limits at infinity",
        instruction_text="Evaluate the limit.",
    ),
    _pc(
        "Introduction to Calculus",
        "pc_definition_of_the_derivative",
        "Definition of the derivative",
        instruction_text="Find the derivative using the definition.",
    ),
    _pc(
        "Introduction to Calculus",
        "pc_instantaneous_rates_of_change",
        "Instantaneous rates of change",
        instruction_text="Find the instantaneous rate of change.",
    ),
    _pc(
        "Introduction to Calculus",
        "pc_power_rule_for_differentiation",
        "Power rule for differentiation",
        instruction_text="Find the derivative.",
    ),
    _pc(
        "Introduction to Calculus",
        "pc_motion_along_a_line",
        "Motion along a line",
        instruction_latex="\\text{Solve the problem.}",
        instruction_text="Solve the problem.",
        count_default=5,
    ),
    _pc(
        "Introduction to Calculus",
        "pc_approximating_area_under_a_curve",
        "Approximating area under a curve",
        instruction_text="Approximate the area.",
    ),
    _pc(
        "Introduction to Calculus",
        "pc_area_under_a_curve_by_limit_of_sums",
        "Area under a curve by limit of sums",
        instruction_text="Find the area.",
    ),
    _pc(
        "Introduction to Calculus",
        "pc_indefinite_integrals",
        "Indefinite integrals",
        instruction_text="Evaluate the integral.",
    ),
)
