"""Catalog generator type: calc_indef_int_logarithmic_rule_and_exponentials_with_substitution."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("calc_indef_int_logarithmic_rule_and_exponentials_with_substitution")
