"""Catalog generator type: calc_app_diff_graphical_comparison_of_f_f_prime_and_f_double_prime."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("calc_app_diff_graphical_comparison_of_f_f_prime_and_f_double_prime")
