"""Graphing catalog type: a2_linear_relations_and_functions_graphing_absolute_value_equations."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_linear_relations_and_functions_graphing_absolute_value_equations")
