"""Catalog generator type: a2_probability_and_statistics_probability_with_permutations_and_combinations."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_probability_and_statistics_probability_with_permutations_and_combinations")
