"""Catalog generator type: a2_probability_and_statistics_probability_of_independent_and_dependent_events_word_problems."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_probability_and_statistics_probability_of_independent_and_dependent_events_word_problems")
