"""Catalog generator type: a2_probability_and_statistics_sample_spaces_and_the_fundamental_counting_principle."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_probability_and_statistics_sample_spaces_and_the_fundamental_counting_principle")
