"""Settings fields for calculus question types."""

from __future__ import annotations

from ...core.models import SettingField


def limit_settings(
    *,
    approach_min_default: int = -5,
    approach_max_default: int = 5,
) -> list[SettingField]:
    return [
        SettingField(
            "limit_approach_min",
            "Approach value min",
            "int",
            approach_min_default,
            min=-20,
            max=20,
            group="limits",
        ),
        SettingField(
            "limit_approach_max",
            "Approach value max",
            "int",
            approach_max_default,
            min=-20,
            max=20,
            group="limits",
        ),
        SettingField(
            "allow_infinity",
            "Include limits at infinity",
            "bool",
            False,
            group="limits",
        ),
        SettingField(
            "coef_min",
            "Coefficient min",
            "int",
            -6,
            min=-20,
            max=20,
            group="limits",
        ),
        SettingField(
            "coef_max",
            "Coefficient max",
            "int",
            6,
            min=-20,
            max=20,
            group="limits",
        ),
        SettingField(
            "power_min",
            "Power min",
            "int",
            1,
            min=0,
            max=6,
            group="limits",
        ),
        SettingField(
            "power_max",
            "Power max",
            "int",
            3,
            min=0,
            max=6,
            group="limits",
        ),
        # Form / method allow-lists (D-gated when allowed)
        SettingField(
            "allow_rational",
            "Allow rational expressions",
            "bool",
            True,
            group="limit_forms",
        ),
        SettingField(
            "allow_removable",
            "Allow removable (factor) forms",
            "bool",
            False,
            group="limit_forms",
        ),
        SettingField(
            "allow_rationalize",
            "Allow rationalize forms",
            "bool",
            False,
            group="limit_forms",
        ),
        SettingField(
            "allow_trig",
            "Allow trigonometric limits",
            "bool",
            False,
            group="limit_forms",
        ),
        SettingField(
            "allow_exp",
            "Allow exponential limits",
            "bool",
            False,
            group="limit_forms",
        ),
        SettingField(
            "allow_log",
            "Allow logarithmic limits",
            "bool",
            False,
            group="limit_forms",
        ),
        SettingField(
            "allow_roots",
            "Allow root / radical forms",
            "bool",
            False,
            group="limit_forms",
        ),
        SettingField(
            "allow_piecewise",
            "Allow piecewise / jump forms",
            "bool",
            False,
            group="limit_forms",
        ),
        SettingField(
            "allow_essential",
            "Allow essential discontinuities",
            "bool",
            False,
            group="limit_forms",
        ),
        SettingField(
            "allow_indet",
            "Allow indeterminate forms",
            "bool",
            False,
            group="limit_methods",
        ),
        SettingField(
            "allow_one_sided",
            "Allow one-sided limits",
            "bool",
            False,
            group="limit_methods",
        ),
        SettingField(
            "apply_lhopital",
            "Apply L'Hôpital's rule",
            "bool",
            False,
            group="limit_methods",
        ),
        SettingField(
            "require_removable",
            "Require removable discontinuity",
            "bool",
            False,
            group="limit_methods",
        ),
        SettingField(
            "require_indet",
            "Require indeterminate form",
            "bool",
            False,
            group="limit_methods",
        ),
        SettingField(
            "max_lhopital_steps",
            "Max L'Hôpital applications",
            "int",
            1,
            min=1,
            max=3,
            group="limit_methods",
        ),
    ]


def derivative_settings(
    *,
    power_min_default: int = 1,
    power_max_default: int = 4,
    term_count_default: int = 2,
) -> list[SettingField]:
    return [
        SettingField(
            "power_min",
            "Power min",
            "int",
            power_min_default,
            min=0,
            max=8,
            group="derivatives",
        ),
        SettingField(
            "power_max",
            "Power max",
            "int",
            power_max_default,
            min=0,
            max=8,
            group="derivatives",
        ),
        SettingField(
            "term_count",
            "Number of terms",
            "int",
            term_count_default,
            min=1,
            max=5,
            group="derivatives",
        ),
        SettingField(
            "coef_min",
            "Coefficient min",
            "int",
            -8,
            min=-20,
            max=20,
            group="derivatives",
        ),
        SettingField(
            "coef_max",
            "Coefficient max",
            "int",
            8,
            min=-20,
            max=20,
            group="derivatives",
        ),
        SettingField(
            "include_constant_term",
            "Include constant terms",
            "bool",
            True,
            group="derivatives",
        ),
        SettingField(
            "variable",
            "Variable",
            "select",
            "x",
            options=["x", "t", "u"],
            group="derivatives",
        ),
        SettingField(
            "allow_trig",
            "Allow trigonometric functions",
            "bool",
            False,
            group="derivative_functions",
        ),
        SettingField(
            "allow_exp",
            "Allow exponential functions",
            "bool",
            False,
            group="derivative_functions",
        ),
        SettingField(
            "allow_log",
            "Allow logarithmic functions",
            "bool",
            False,
            group="derivative_functions",
        ),
        SettingField(
            "allow_hyperbolic",
            "Allow hyperbolic functions",
            "bool",
            False,
            group="derivative_functions",
        ),
        SettingField(
            "allow_roots",
            "Allow root / fractional-power forms",
            "bool",
            False,
            group="derivative_functions",
        ),
        SettingField(
            "allow_invtrig",
            "Allow inverse trigonometric functions",
            "bool",
            False,
            group="derivative_functions",
        ),
        # Method allow / require flags (methods may still soft-unlock with D)
        SettingField(
            "allow_chain",
            "Allow chain rule",
            "bool",
            False,
            group="derivative_methods",
        ),
        SettingField(
            "allow_product",
            "Allow product rule",
            "bool",
            False,
            group="derivative_methods",
        ),
        SettingField(
            "allow_quotient",
            "Allow quotient rule",
            "bool",
            False,
            group="derivative_methods",
        ),
        SettingField(
            "allow_implicit",
            "Allow implicit differentiation",
            "bool",
            False,
            group="derivative_methods",
        ),
        SettingField(
            "require_chain",
            "Require chain rule",
            "bool",
            False,
            group="derivative_methods",
        ),
        SettingField(
            "require_product",
            "Require product rule",
            "bool",
            False,
            group="derivative_methods",
        ),
        SettingField(
            "require_quotient",
            "Require quotient rule",
            "bool",
            False,
            group="derivative_methods",
        ),
        SettingField(
            "require_implicit",
            "Require implicit differentiation",
            "bool",
            False,
            group="derivative_methods",
        ),
        SettingField(
            "allow_triple_product",
            "Allow three-factor products",
            "bool",
            False,
            group="derivative_methods",
        ),
        # Exponent-style knobs (None/default → pack D presets; explicit bool overrides)
        SettingField(
            "allow_integer_exponents",
            "Allow integer exponents",
            "bool",
            True,
            group="derivative_exponents",
        ),
        SettingField(
            "allow_fractional_exponents",
            "Allow fractional exponents",
            "bool",
            False,
            group="derivative_exponents",
        ),
        SettingField(
            "allow_irrational_exponents",
            "Allow irrational exponents (π, e, √2, …)",
            "bool",
            False,
            group="derivative_exponents",
        ),
        SettingField(
            "allow_negative_exponents",
            "Allow negative exponents",
            "bool",
            False,
            group="derivative_exponents",
        ),
    ]


def integral_settings(
    *,
    power_min_default: int = 1,
    power_max_default: int = 4,
    term_count_default: int = 2,
) -> list[SettingField]:
    return [
        SettingField(
            "power_min",
            "Power min",
            "int",
            power_min_default,
            min=0,
            max=8,
            group="integrals",
        ),
        SettingField(
            "power_max",
            "Power max",
            "int",
            power_max_default,
            min=0,
            max=8,
            group="integrals",
        ),
        SettingField(
            "term_count",
            "Number of terms",
            "int",
            term_count_default,
            min=1,
            max=5,
            group="integrals",
        ),
        SettingField(
            "coef_min",
            "Coefficient min",
            "int",
            -8,
            min=-20,
            max=20,
            group="integrals",
        ),
        SettingField(
            "coef_max",
            "Coefficient max",
            "int",
            8,
            min=-20,
            max=20,
            group="integrals",
        ),
        SettingField(
            "include_constant_term",
            "Include constant terms",
            "bool",
            True,
            group="integrals",
        ),
        SettingField(
            "require_positive_power",
            "Require positive power (avoid 1/x)",
            "bool",
            True,
            group="integrals",
        ),
        SettingField(
            "variable",
            "Variable",
            "select",
            "x",
            options=["x", "t", "u"],
            group="integrals",
        ),
        # Technique / function allow-lists
        SettingField(
            "allow_trig",
            "Allow trigonometric integrands",
            "bool",
            False,
            group="integral_functions",
        ),
        SettingField(
            "allow_exp",
            "Allow exponential integrands",
            "bool",
            False,
            group="integral_functions",
        ),
        SettingField(
            "allow_log",
            "Allow logarithmic integrands",
            "bool",
            False,
            group="integral_functions",
        ),
        SettingField(
            "allow_invtrig",
            "Allow inverse-trig integrands",
            "bool",
            False,
            group="integral_functions",
        ),
        SettingField(
            "allow_substitution",
            "Allow u-substitution",
            "bool",
            False,
            group="integral_techniques",
        ),
        SettingField(
            "allow_parts",
            "Allow integration by parts",
            "bool",
            False,
            group="integral_techniques",
        ),
        SettingField(
            "allow_pfd",
            "Allow partial fractions",
            "bool",
            False,
            group="integral_techniques",
        ),
        SettingField(
            "allow_trig_sub",
            "Allow trigonometric substitution",
            "bool",
            False,
            group="integral_techniques",
        ),
        SettingField(
            "allow_ftc",
            "Allow FTC / definite evaluation",
            "bool",
            False,
            group="integral_techniques",
        ),
        SettingField(
            "require_substitution",
            "Require u-substitution",
            "bool",
            False,
            group="integral_techniques",
        ),
        SettingField(
            "require_parts",
            "Require integration by parts",
            "bool",
            False,
            group="integral_techniques",
        ),
        SettingField(
            "require_pfd",
            "Require partial fractions",
            "bool",
            False,
            group="integral_techniques",
        ),
        SettingField(
            "require_trig",
            "Require trigonometric integrand",
            "bool",
            False,
            group="integral_techniques",
        ),
        SettingField(
            "require_trig_sub",
            "Require trigonometric substitution",
            "bool",
            False,
            group="integral_techniques",
        ),
        SettingField(
            "include_plus_c",
            "Include +C on indefinite answers",
            "bool",
            True,
            group="integrals",
        ),
        SettingField(
            "definite",
            "Generate definite integrals",
            "bool",
            False,
            group="integrals",
        ),
        SettingField(
            "max_pipeline_len",
            "Max trick pipeline length",
            "int",
            1,
            min=1,
            max=3,
            group="integral_techniques",
        ),
    ]
