"""Catalog generator type: geo_probability_independent_and_dependent_events_word_problems."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("geo_probability_independent_and_dependent_events_word_problems")
