"""Catalog generator type: geo_similarity_proportional_parts_in_triangles_and_parallel_lines."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("geo_similarity_proportional_parts_in_triangles_and_parallel_lines")
