import type { CurriculumLevel } from "@/lib/types";

export const CURRICULUM: CurriculumLevel[] = [
  {
    id: "grade_6_math",
    name: "Grade 6 Math",
    topics: [
      {
        id: "ratios",
        name: "Ratios",
        topics: [
          { id: "g6_introduction_to_ratios", name: "Introduction to ratios", type_id: "g6_introduction_to_ratios" },
          { id: "g6_equivalent_ratios", name: "Equivalent ratios", type_id: "g6_equivalent_ratios" },
          { id: "g6_part_part_whole_ratios", name: "Part-part-whole ratios", type_id: "g6_part_part_whole_ratios" },
          { id: "g6_comparing_ratios", name: "Comparing ratios", type_id: "g6_equivalent_ratios" },
        ],
      },
      {
        id: "rates",
        name: "Rates",
        topics: [
          { id: "g6_unit_rates_and_equivalent_rates", name: "Unit rates and equivalent rates", type_id: "g6_unit_rates_and_equivalent_rates" },
          { id: "g6_comparing_rates", name: "Comparing rates", type_id: "g6_comparing_rates" },
          { id: "g6_converting_units", name: "Converting units", type_id: "g6_converting_units" },
        ],
      },
      {
        id: "percents",
        name: "Percents",
        topics: [
          { id: "g6_introduction_to_percents", name: "Introduction to percents", type_id: "g6_introduction_to_percents" },
          {
            id: "g6_relating_percents_fractions_and_decimals",
            name: "Relating percents, fractions, and decimals", type_id: "g6_relating_percents_fractions_and_decimals" },
          {
            id: "g6_finding_percents_with_equivalent_fractions",
            name: "Finding percents with equivalent fractions", type_id: "g6_finding_percents_with_equivalent_fractions" },
          {
            id: "g6_solving_percent_problems_with_diagrams",
            name: "Solving percent problems with diagrams",
          },
          {
            id: "g6_solving_percent_problems_with_formulas",
            name: "Solving percent problems with formulas", type_id: "g6_solving_percent_problems_with_formulas" },
        ],
      },
      {
        id: "dividing_fractions",
        name: "Dividing Fractions",
        topics: [
          { id: "g6_how_many_groups_times", name: "How many groups/times?", type_id: "g6_how_many_groups_times" },
          { id: "g6_what_fraction_of_a_whole", name: "What fraction of a whole?", type_id: "g6_what_fraction_of_a_whole" },
          { id: "g6_how_much_in_each_group_time", name: "How much in each group/time?", type_id: "g6_how_much_in_each_group_time" },
          { id: "g6_dividing_fractions", name: "Dividing fractions", type_id: "g6_dividing_fractions" },
        ],
      },
      {
        id: "decimal_arithmetic",
        name: "Decimal Arithmetic",
        topics: [
          { id: "g6_decimal_addition_with_diagrams", name: "Decimal addition with diagrams", type_id: "g6_decimal_addition_with_diagrams" },
          { id: "g6_decimal_addition", name: "Decimal addition", type_id: "g6_decimal_addition" },
          { id: "g6_decimal_subtraction_with_diagrams", name: "Decimal subtraction with diagrams", type_id: "g6_decimal_subtraction_with_diagrams" },
          { id: "g6_decimal_subtraction", name: "Decimal subtraction", type_id: "g6_decimal_subtraction" },
          {
            id: "g6_decimal_multiplication_with_equivalent_fractions",
            name: "Decimal multiplication with equivalent fractions", type_id: "g6_decimal_multiplication_with_equivalent_fractions" },
          {
            id: "g6_decimal_multiplication_with_area_diagrams",
            name: "Decimal multiplication with area diagrams", type_id: "g6_decimal_multiplication_with_area_diagrams" },
          { id: "g6_decimal_multiplication", name: "Decimal multiplication", type_id: "g6_decimal_multiplication" },
          { id: "g6_long_division_with_remainders", name: "Long division with remainders", type_id: "g6_long_division_with_remainders" },
          {
            id: "g6_dividing_whole_numbers_that_result_in_decimals",
            name: "Dividing whole numbers that result in decimals", type_id: "g6_dividing_whole_numbers_that_result_in_decimals" },
          { id: "g6_dividing_decimals_by_whole_numbers", name: "Dividing decimals by whole numbers", type_id: "g6_dividing_decimals_by_whole_numbers" },
          { id: "g6_dividing_whole_numbers_by_decimals", name: "Dividing whole numbers by decimals", type_id: "g6_dividing_whole_numbers_by_decimals" },
          { id: "g6_dividing_decimals_by_decimals", name: "Dividing decimals by decimals" },
        ],
      },
      {
        id: "common_factors_and_common_multiples",
        name: "Common Factors and Common Multiples",
        topics: [
          { id: "g6_factoring", name: "Factoring", type_id: "g6_factoring" },
          { id: "g6_greatest_common_factor", name: "Greatest common factor", type_id: "g6_greatest_common_factor" },
          { id: "g6_least_common_multiple", name: "Least common multiple", type_id: "g6_least_common_multiple" },
          { id: "g6_gcf_and_lcm_word_problems", name: "GCF and LCM word problems", type_id: "g6_gcf_and_lcm_word_problems" },
        ],
      },
      {
        id: "negative_numbers_and_absolute_value",
        name: "Negative Numbers and Absolute Value",
        topics: [
          { id: "g6_numbers_on_a_number_line", name: "Numbers on a number line", type_id: "g6_numbers_on_a_number_line" },
          { id: "g6_number_line_word_problems", name: "Number line word problems", type_id: "g6_number_line_word_problems" },
          { id: "g6_opposites_of_numbers", name: "Opposites of numbers", type_id: "g6_opposites_of_numbers" },
          { id: "g6_comparing_numbers", name: "Comparing numbers", type_id: "g6_comparing_numbers" },
          { id: "g6_ordering_numbers", name: "Ordering numbers", type_id: "g6_ordering_numbers" },
          { id: "g6_absolute_values", name: "Absolute values", type_id: "g6_absolute_values" },
          { id: "g6_comparing_with_absolute_values", name: "Comparing with absolute values", type_id: "g6_comparing_with_absolute_values" },
          { id: "g6_ordering_with_absolute_values", name: "Ordering with absolute values", type_id: "g6_ordering_with_absolute_values" },
        ],
      },
      {
        id: "coordinate_plane",
        name: "Coordinate Plane",
        topics: [
          { id: "g6_points_on_the_coordinate_plane", name: "Points on the coordinate plane", type_id: "g6_points_on_the_coordinate_plane" },
          { id: "g6_distances_on_the_coordinate_plane", name: "Distances on the coordinate plane", type_id: "g6_distances_on_the_coordinate_plane" },
          {
            id: "g6_shapes_and_perimeter_on_the_coordinate_plane",
            name: "Shapes and perimeter on the coordinate plane", type_id: "g6_shapes_and_perimeter_on_the_coordinate_plane" },
          { id: "g6_coordinate_plane_distances_word_problems", name: "Distances, word problems", type_id: "g6_coordinate_plane_distances_word_problems" },
        ],
      },
      {
        id: "numeric_expressions_exponents_and_order_of_operations",
        name: "Numeric Expressions, Exponents, and the Order of Operations",
        topics: [
          { id: "g6_writing_numeric_expressions", name: "Writing numeric expressions", type_id: "g6_writing_numeric_expressions" },
          { id: "g6_numeric_expressions_with_exponents", name: "Numeric expressions with exponents", type_id: "g6_numeric_expressions_with_exponents" },
          {
            id: "g6_properties_of_addition_and_multiplication",
            name: "Properties of addition and multiplication", type_id: "g6_properties_of_addition_and_multiplication" },
          {
            id: "g6_numeric_expressions_and_order_of_operations",
            name: "Numeric expressions and the order of operations", type_id: "g6_numeric_expressions_and_order_of_operations" },
          {
            id: "g6_distributive_property_area_diagrams_numeric",
            name: "Distributive property with area diagrams, numeric", type_id: "g6_distributive_property_area_diagrams_numeric" },
          { id: "g6_distributive_property_numeric", name: "Distributive property, numeric", type_id: "distributive_property" },
        ],
      },
      {
        id: "variables_and_algebraic_expressions",
        name: "Variables and Algebraic Expressions",
        topics: [
          { id: "g6_writing_algebraic_expressions", name: "Writing algebraic expressions", type_id: "g6_writing_algebraic_expressions" },
          { id: "g6_evaluating_algebraic_expressions", name: "Evaluating algebraic expressions", type_id: "g6_evaluating_algebraic_expressions" },
        ],
      },
      {
        id: "equivalent_expressions",
        name: "Equivalent Expressions",
        topics: [
          { id: "g6_combining_like_terms", name: "Combining like terms", type_id: "g6_combining_like_terms" },
          {
            id: "g6_distributive_property_area_diagrams_algebraic",
            name: "Distributive property with area diagrams, algebraic",
          },
          { id: "g6_distributive_property_algebraic", name: "Distributive property, algebraic", type_id: "distributive_property" },
        ],
      },
      {
        id: "equations",
        name: "Equations",
        topics: [
          { id: "g6_solutions_to_equations", name: "Solutions to equations", type_id: "g6_solutions_to_equations" },
          { id: "g6_equations_tape_diagrams", name: "Tape diagrams" },
          { id: "g6_equations_hanger_diagrams", name: "Hanger diagrams" },
          { id: "g6_equations_word_problems", name: "Equations word problems", type_id: "g6_equations_word_problems" },
        ],
      },
      {
        id: "inequalities",
        name: "Inequalities",
        topics: [
          { id: "g6_solutions_to_inequalities", name: "Solutions to inequalities", type_id: "g6_solutions_to_inequalities" },
          { id: "g6_writing_and_graphing_inequalities", name: "Writing and graphing inequalities", type_id: "g6_writing_and_graphing_inequalities" },
          { id: "g6_inequalities_word_problems", name: "Inequalities word problems", type_id: "g6_inequalities_word_problems" },
          {
            id: "g6_solving_and_graphing_one_step_inequalities",
            name: "Solving and graphing one-step inequalities", type_id: "one_step_inequalities" },
          { id: "g6_inequalities_hanger_diagrams", name: "Hanger diagrams" },
        ],
      },
      {
        id: "equations_as_relationships_between_two_variables",
        name: "Equations as Relationships between Two Variables",
        topics: [
          { id: "g6_equivalent_ratio_equations", name: "Equivalent ratio equations", type_id: "g6_equivalent_ratio_equations" },
          { id: "g6_constant_rate_equations", name: "Constant rate equations", type_id: "g6_constant_rate_equations" },
          { id: "g6_equations_for_other_relationships", name: "Equations for other relationships", type_id: "g6_equations_for_other_relationships" },
        ],
      },
      {
        id: "polygons",
        name: "Polygons",
        topics: [
          {
            id: "g6_parallelograms_understanding_area_formula",
            name: "Parallelograms, understanding area formula",
          },
          { id: "g6_parallelograms", name: "Parallelograms" },
          { id: "g6_triangles_understanding_area_formula", name: "Triangles, understanding area formula" },
          { id: "g6_triangles", name: "Triangles" },
          { id: "g6_trapezoids", name: "Trapezoids" },
          { id: "g6_kites", name: "Kites" },
          {
            id: "g6_polygons_on_a_grid_or_coordinate_plane",
            name: "Polygons on a grid or coordinate plane",
          },
          { id: "g6_polygons_and_shaded_regions", name: "Polygons and shaded regions" },
        ],
      },
      {
        id: "polyhedra",
        name: "Polyhedra",
        topics: [
          { id: "g6_classifying_and_naming", name: "Classifying and naming" },
          { id: "g6_nets", name: "Nets" },
          { id: "g6_nets_and_surface_area", name: "Nets and surface area" },
          { id: "g6_nets_and_surface_area_on_a_grid", name: "Nets and surface area on a grid" },
          { id: "g6_identifying_invalid_nets", name: "Identifying invalid nets" },
          {
            id: "g6_volume_and_surface_area_using_isometric_drawings",
            name: "Volume and surface area using isometric drawings",
          },
          {
            id: "g6_formulas_for_volume_and_surface_area_of_a_cube",
            name: "Formulas for volume and surface area of a cube",
          },
          { id: "g6_isometric_sketching", name: "Isometric sketching" },
        ],
      },
      {
        id: "area_and_volume_with_fractions",
        name: "Area and Volume with Fractions",
        topics: [
          {
            id: "g6_rectangles_with_fraction_side_lengths",
            name: "Rectangles with fraction side lengths",
          },
          { id: "g6_triangles_with_fraction_side_lengths", name: "Triangles with fraction side lengths" },
          {
            id: "g6_right_rectangular_prisms_with_fraction_side_lengths",
            name: "Right rectangular prisms with fraction side lengths",
          },
        ],
      },
      {
        id: "data_sets_and_distributions",
        name: "Data Sets and Distributions",
        topics: [
          { id: "g6_interpreting_dot_plots", name: "Interpreting dot plots", type_id: "g6_interpreting_dot_plots" },
          { id: "g6_drawing_dot_plots", name: "Drawing dot plots" },
          { id: "g6_interpreting_histograms", name: "Interpreting histograms", type_id: "g6_interpreting_histograms" },
          { id: "g6_drawing_histograms", name: "Drawing histograms" },
          { id: "g6_data_center_and_spread", name: "Center and spread", type_id: "g6_data_center_and_spread" },
          { id: "g6_interpreting_box_plots", name: "Interpreting box plots", type_id: "g6_interpreting_box_plots" },
          { id: "g6_drawing_box_plots", name: "Drawing box plots", type_id: "g6_drawing_box_plots" },
        ],
      },
    ],
  },
  {
    id: "pre_algebra",
    name: "Pre-Algebra",
    topics: [
      {
        id: "integers_decimals_and_fractions",
        name: "Integers, Decimals, and Fractions",
        topics: [
          {
            id: "pa_naming_decimal_places_and_rounding",
            name: "Naming decimal places and rounding", type_id: "pa_naming_decimal_places_and_rounding" },
          { id: "pa_writing_numbers_with_words", name: "Writing numbers with words" },
          { id: "pa_integers_adding_and_subtracting", name: "Adding and subtracting", type_id: "rational_add_subtract" },
          { id: "pa_integers_multiplying", name: "Multiplying", type_id: "rational_multiply" },
          { id: "pa_integers_dividing", name: "Dividing", type_id: "rational_divide" },
          { id: "pa_factoring", name: "Factoring" },
          { id: "pa_greatest_common_factor", name: "Greatest common factor", type_id: "pa_greatest_common_factor" },
          { id: "pa_least_common_multiple", name: "Least common multiple", type_id: "pa_least_common_multiple" },
          { id: "pa_simplifying_fractions", name: "Simplifying fractions", type_id: "pa_simplifying_fractions" },
          {
            id: "pa_converting_fractions_and_decimals",
            name: "Converting fractions and decimals",
          },
        ],
      },
      {
        id: "beginning_algebra",
        name: "Beginning Algebra",
        topics: [
          { id: "verbal_expressions", name: "Verbal expressions", type_id: "verbal_expressions" },
          { id: "order_of_operations", name: "Order of operations", type_id: "order_of_operations" },
          { id: "distributive_property", name: "The Distributive Property", type_id: "distributive_property" },
        ],
      },
      {
        id: "equations",
        name: "Equations",
        topics: [
          { id: "one_step_equations", name: "One-step equations", type_id: "one_step_equations" },
          {
            id: "pa_equations_one_step_word_problems",
            name: "One-step equations, word problems", type_id: "pa_equations_one_step_word_problems" },
          { id: "two_step_equations", name: "Two-step equations", type_id: "two_step_equations" },
          {
            id: "pa_equations_two_step_word_problems",
            name: "Two-step equations word problems", type_id: "pa_equations_two_step_word_problems" },
          { id: "pa_equations_multi_step_equations", name: "Multi-step equations", type_id: "multi_step_equations" },
        ],
      },
      {
        id: "inequalities",
        name: "Inequalities",
        topics: [
          {
            id: "graphing_single_variable_inequalities",
            name: "Graphing single-variable inequalities", type_id: "graphing_single_variable_inequalities" },
          { id: "one_step_inequalities", name: "One-step inequalities", type_id: "one_step_inequalities" },
          { id: "two_step_inequalities", name: "Two-step inequalities", type_id: "two_step_inequalities" },
          { id: "pa_multi_step_inequalities", name: "Multi-step inequalities", type_id: "multi_step_inequalities" },
        ],
      },
      {
        id: "factors_and_exponents",
        name: "Factors and Exponents",
        topics: [
          { id: "pa_divisibility", name: "Divisibility", type_id: "pa_divisibility" },
          { id: "properties_of_exponents", name: "Properties of exponents", type_id: "properties_of_exponents" },
          { id: "scientific_notation_write", name: "Writing scientific notation", type_id: "scientific_notation_write" },
          {
            id: "scientific_notation_operations",
            name: "Operations and scientific notation", type_id: "scientific_notation_operations" },
        ],
      },
      {
        id: "proportions_and_similarity",
        name: "Proportions and Similarity",
        topics: [
          { id: "pa_checking_for_a_proportion", name: "Checking for a proportion", type_id: "solving_proportions" },
          { id: "solving_proportions", name: "Solving proportions", type_id: "solving_proportions" },
          { id: "pa_proportions_word_problems", name: "Proportions word problems", type_id: "pa_proportions_word_problems" },
          { id: "pa_similar_figures", name: "Similar figures", type_id: "pa_similar_figures" },
          { id: "pa_similar_figures_word_problems", name: "Similar figures word problems", type_id: "pa_similar_figures_word_problems" },
        ],
      },
      {
        id: "percents",
        name: "Percents",
        topics: [
          {
            id: "pa_fractions_decimals_and_percents",
            name: "Fractions, decimals, and percents",
          },
          { id: "percents", name: "Percents", type_id: "percents" },
          { id: "percent_of_change", name: "Percent of change", type_id: "percent_of_change" },
          { id: "pa_markup_discount_and_tax", name: "Markup, discount, and tax", type_id: "pa_markup_discount_and_tax" },
          { id: "pa_simple_and_compound_interest", name: "Simple and compound interest", type_id: "pa_simple_and_compound_interest" },
        ],
      },
      {
        id: "linear_equations_and_inequalities",
        name: "Linear Equations and Inequalities",
        topics: [
          { id: "pa_plotting_points", name: "Plotting points", type_id: "pa_plotting_points" },
          { id: "radical_midpoint_formula", name: "The Midpoint Formula", type_id: "radical_midpoint_formula" },
          { id: "slope", name: "Slope", type_id: "slope" },
          { id: "graphing_linear_equations", name: "Graphing linear equations", type_id: "graphing_linear_equations" },
          { id: "writing_linear_equations", name: "Writing linear equations", type_id: "writing_linear_equations" },
          { id: "graphing_linear_inequalities", name: "Graphing linear inequalities", type_id: "graphing_linear_inequalities" },
          {
            id: "pa_graphing_systems_of_equations",
            name: "Graphing systems of equations", type_id: "pa_graphing_systems_of_equations" },
          {
            id: "pa_systems_substitution",
            name: "Solving systems of equations by substitution", type_id: "systems_substitution" },
          { id: "pa_systems_word_problems", name: "Systems of equations word problems", type_id: "pa_systems_word_problems" },
        ],
      },
      {
        id: "plane_figures",
        name: "Plane Figures",
        topics: [
          {
            id: "pa_drawing_and_measuring_angles",
            name: "Drawing and measuring angles",
          },
          { id: "pa_angle_relationships", name: "Angle relationships" },
          { id: "pa_plane_figures_triangles", name: "Triangles" },
          { id: "pa_quadrilaterals", name: "Quadrilaterals" },
          {
            id: "pa_area_of_triangles_and_quadrilaterals",
            name: "Area of triangles and quadrilaterals", type_id: "pa_area_of_triangles_and_quadrilaterals" },
          { id: "pa_circles", name: "Circles" },
          { id: "pa_transformations", name: "Transformations", type_id: "pa_transformations" },
        ],
      },
      {
        id: "solid_figures",
        name: "Solid Figures",
        topics: [
          {
            id: "pa_classifying_volume_and_surface_area",
            name: "Classifying, volume, and surface area",
          },
        ],
      },
      {
        id: "right_triangles",
        name: "Right Triangles",
        topics: [
          { id: "pa_squares_and_square_roots", name: "Squares and square roots", type_id: "radical_simplification" },
          { id: "pythagorean_theorem", name: "The Pythagorean Theorem", type_id: "pythagorean_theorem" },
          { id: "radical_distance_formula", name: "The Distance Formula", type_id: "radical_distance_formula" },
        ],
      },
      {
        id: "beginning_polynomials",
        name: "Beginning Polynomials",
        topics: [
          { id: "pa_polynomials_adding_and_subtracting", name: "Adding and subtracting", type_id: "pa_polynomials_adding_and_subtracting" },
          { id: "pa_polynomials_multiplying", name: "Multiplying", type_id: "pa_polynomials_multiplying" },
        ],
      },
      {
        id: "statistics",
        name: "Statistics",
        topics: [
          { id: "visualizing_data", name: "Visualizing data", type_id: "visualizing_data" },
          { id: "center_and_spread", name: "Center and spread", type_id: "center_and_spread" },
          { id: "scatter_plots", name: "Scatter plots", type_id: "scatter_plots" },
          { id: "using_statistical_models", name: "Using statistical models" },
        ],
      },
    ],
  },
  {
    id: "algebra_1",
    name: "Algebra 1",
    topics: [
      {
        id: "beginning_algebra",
        name: "Beginning Algebra",
        topics: [
          { id: "verbal_expressions", name: "Verbal expressions", type_id: "verbal_expressions" },
          { id: "order_of_operations", name: "Order of operations", type_id: "order_of_operations" },
          { id: "sets_of_numbers", name: "Sets of numbers", type_id: "sets_of_numbers" },
          { id: "adding_and_subtracting_rational_numbers", name: "Adding and subtracting rational numbers", type_id: "rational_add_subtract" },
          { id: "multiplying_rational_numbers", name: "Multiplying rational numbers", type_id: "rational_multiply" },
          { id: "dividing_rational_numbers", name: "Dividing rational numbers", type_id: "rational_divide" },
          { id: "the_distributive_property", name: "The Distributive Property", type_id: "distributive_property" },
        ],
      },
      {
        id: "equations",
        name: "Equations",
        topics: [
          { id: "one_step_equations", name: "One-step equations", type_id: "one_step_equations" },
          { id: "two_step_equations", name: "Two-step equations", type_id: "two_step_equations" },
          { id: "multi_step_equations", name: "Multi-step equations", type_id: "multi_step_equations" },
          { id: "absolute_value_equations", name: "Absolute value equations", type_id: "absolute_value_equations" },
          { id: "mixture_word_problems", name: "Mixture word problems", type_id: "mixture_word_problems" },
          { id: "distance_rate_time_word_problems", name: "Distance, rate, time word problems", type_id: "distance_rate_time_word_problems" },
          { id: "work_word_problems", name: "Work word problems", type_id: "work_word_problems" },
          { id: "literal_equations", name: "Literal equations", type_id: "literal_equations" },
        ],
      },
      {
        id: "inequalities",
        name: "Inequalities",
        topics: [
          { id: "graphing_single_variable_inequalities", name: "Graphing single-variable inequalities", type_id: "graphing_single_variable_inequalities" },
          { id: "one_step_inequalities", name: "One-step inequalities", type_id: "one_step_inequalities" },
          { id: "two_step_inequalities", name: "Two-step inequalities", type_id: "two_step_inequalities" },
          { id: "multi_step_inequalities", name: "Multi-step inequalities", type_id: "multi_step_inequalities" },
          { id: "compound_inequalities", name: "Compound inequalities", type_id: "compound_inequalities" },
          { id: "absolute_value_inequalities", name: "Absolute value inequalities", type_id: "absolute_value_inequalities" },
        ],
      },
      {
        id: "proportions_and_percents",
        name: "Proportions and Percents",
        topics: [
          { id: "solving_proportions", name: "Solving proportions", type_id: "solving_proportions" },
          { id: "percents", name: "Percents", type_id: "percents" },
          { id: "percent_of_change", name: "Percent of change", type_id: "percent_of_change" },
        ],
      },
      {
        id: "relations_and_introduction_to_functions",
        name: "Relations and Introduction to Functions",
        topics: [
          { id: "discrete_relations", name: "Discrete relations", type_id: "discrete_relations" },
          { id: "continuous_relations", name: "Continuous relations", type_id: "continuous_relations" },
          { id: "evaluating_and_graphing_functions", name: "Evaluating and graphing functions", type_id: "evaluating_graphing_functions" },
        ],
      },
      {
        id: "linear_equations_and_inequalities",
        name: "Linear Equations and Inequalities",
        topics: [
          { id: "slope", name: "Slope", type_id: "slope" },
          { id: "more_on_slope", name: "More on slope", type_id: "more_on_slope" },
          { id: "graphing_linear_equations", name: "Graphing linear equations", type_id: "graphing_linear_equations" },
          { id: "writing_linear_equations", name: "Writing linear equations", type_id: "writing_linear_equations" },
          { id: "graphing_linear_inequalities", name: "Graphing linear inequalities", type_id: "graphing_linear_inequalities" },
          { id: "graphing_absolute_value_equations", name: "Graphing absolute value equations", type_id: "graphing_absolute_value_equations" },
        ],
      },
      {
        id: "direct_and_inverse_variation",
        name: "Direct and inverse variation",
        topics: [{ id: "direct_and_inverse_variation", name: "Direct and inverse variation", type_id: "direct_inverse_variation" }],
      },
      {
        id: "systems_of_equations_and_inequalities",
        name: "Systems of Equations and Inequalities",
        topics: [
          { id: "solving_by_graphing", name: "Solving by graphing", type_id: "systems_graphing" },
          { id: "solving_by_elimination", name: "Solving by elimination", type_id: "systems_elimination" },
          { id: "solving_by_substitution", name: "Solving by substitution", type_id: "systems_substitution" },
          { id: "graphing_systems_of_inequalities", name: "Graphing systems of inequalities", type_id: "graphing_systems_of_inequalities" },
          { id: "systems_word_problems", name: "Word problems", type_id: "systems_word_problems" },
        ],
      },
      {
        id: "exponents",
        name: "Exponents",
        topics: [
          { id: "properties_of_exponents", name: "Properties of exponents", type_id: "properties_of_exponents" },
          { id: "graphing_exponential_functions", name: "Graphing exponential functions", type_id: "graphing_exponential_functions" },
          { id: "writing_scientific_notation", name: "Writing scientific notation", type_id: "scientific_notation_write" },
          { id: "operations_and_scientific_notation", name: "Operations and scientific notation", type_id: "scientific_notation_operations" },
          {
            id: "addition_subtraction_and_scientific_notation",
            name: "Addition/Subtraction and scientific notation", type_id: "scientific_notation_add_subtract" },
          {
            id: "discrete_exponential_growth_and_decay_word_problems",
            name: "Discrete exponential growth and decay word problems", type_id: "exponential_growth_decay" },
        ],
      },
      {
        id: "polynomials",
        name: "Polynomials",
        topics: [
          { id: "polynomials_naming", name: "Naming", type_id: "polynomial_naming" },
          { id: "polynomials_adding_and_subtracting", name: "Adding and subtracting", type_id: "polynomial_add_subtract" },
          { id: "polynomials_dividing", name: "Dividing", type_id: "polynomial_long_division" },
          { id: "polynomials_multiplying", name: "Multiplying", type_id: "polynomial_multiply" },
          { id: "polynomials_multiplying_special_cases", name: "Multiplying special cases", type_id: "polynomial_multiply_special" },
          {
            id: "factoring",
            name: "Factoring",
            topics: [
              { id: "common_factor_only", name: "Common factor only", type_id: "polynomial_factoring_common_factor" },
              { id: "quadratic_expressions", name: "Quadratic expressions", type_id: "quadratic_factoring" },
              { id: "factoring_special_cases", name: "Special cases", type_id: "polynomial_factoring_special_cases" },
              { id: "factoring_by_grouping", name: "By grouping", type_id: "polynomial_factoring_grouping" },
            ],
          },
        ],
      },
      {
        id: "quadratic_functions",
        name: "Quadratic Functions",
        topics: [
          { id: "graphing_quadratic_functions", name: "Graphing", type_id: "graphing_quadratic_functions" },
          { id: "graphing_quadratic_inequalities", name: "Graphing quadratic inequalities", type_id: "graphing_quadratic_inequalities" },
          { id: "solving_equations_by_taking_square_roots", name: "Solving equations by taking square roots", type_id: "quadratic_square_roots" },
          { id: "solving_equations_by_factoring", name: "Solving equations by factoring", type_id: "quadratic_factoring_equations" },
      {
        id: "solving_equations_with_the_quadratic_formula",
            name: "Solving equations with the Quadratic Formula", type_id: "quadratic_formula" },
          { id: "understanding_the_discriminant", name: "Understanding the discriminant", type_id: "quadratic_discriminant" },
      {
        id: "completing_the_square_by_finding_the_constant",
            name: "Completing the square by finding the constant", type_id: "quadratic_completing_square_constant" },
          { id: "solving_equations_by_completing_the_square", name: "Solving equations by completing the square", type_id: "quadratic_completing_square_solve" },
        ],
      },
      {
        id: "radical_expressions",
        name: "Radical Expressions",
        topics: [
          { id: "simplifying_single_radicals", name: "Simplifying single radicals", type_id: "radical_simplification" },
          { id: "the_distance_formula", name: "The Distance Formula", type_id: "radical_distance_formula" },
          { id: "the_midpoint_formula", name: "The Midpoint Formula", type_id: "radical_midpoint_formula" },
          { id: "radical_expressions_adding_and_subtracting", name: "Adding and subtracting", type_id: "radical_add_subtract" },
          { id: "radical_expressions_multiplying", name: "Multiplying", type_id: "radical_multiply" },
          { id: "radical_expressions_dividing", name: "Dividing", type_id: "radical_divide" },
          { id: "radical_expressions_equations", name: "Equations", type_id: "radical_equations" },
        ],
      },
      {
        id: "rational_expressions",
        name: "Rational Expressions",
        topics: [
          { id: "simplifying_and_excluded_values", name: "Simplifying and excluded values", type_id: "rational_simplification" },
          { id: "rational_expressions_multiplying_and_dividing", name: "Multiplying and dividing", type_id: "rational_expression_multiply_divide" },
          { id: "rational_expressions_adding_and_subtracting", name: "Adding and subtracting", type_id: "rational_expression_simplification" },
          { id: "rational_expressions_equations", name: "Equations", type_id: "rational_expressions_equations" },
        ],
      },
      {
        id: "beginning_trigonometry",
        name: "Beginning Trigonometry",
        topics: [
          { id: "finding_sine_cosine_tangent", name: "Finding sine, cosine, tangent", type_id: "finding_sine_cosine_tangent" },
          { id: "finding_angles", name: "Finding angles", type_id: "finding_angles" },
          { id: "find_missing_sides_of_triangles", name: "Find missing sides of triangles", type_id: "find_missing_sides_of_triangles" },
        ],
      },
      {
        id: "statistics",
        name: "Statistics",
        topics: [
          { id: "visualizing_data", name: "Visualizing data", type_id: "visualizing_data" },
          { id: "center_and_spread", name: "Center and spread", type_id: "center_and_spread" },
          { id: "scatter_plots", name: "Scatter plots", type_id: "scatter_plots" },
          { id: "using_statistical_models", name: "Using statistical models" },
        ],
      },
    ],
  },
  {
    id: "algebra_2",
    name: "Algebra 2",
    topics: [
      {
        id: "beginning_algebra",
        name: "Beginning Algebra",
        topics: [
          { id: "a2_beginning_algebra_order_of_operations", name: "Order of operations", type_id: "order_of_operations" },
          { id: "a2_beginning_algebra_simplifying_algebraic_expressions", name: "Simplifying algebraic expressions", type_id: "a2_beginning_algebra_simplifying_algebraic_expressions" },
        ],
      },
      {
        id: "equations_and_inequalities",
        name: "Equations and Inequalities",
        topics: [
          { id: "a2_equations_and_inequalities_multi_step_equations", name: "Multi-step equations", type_id: "multi_step_equations" },
          { id: "a2_equations_and_inequalities_work_word_problems", name: "Work word problems", type_id: "a2_equations_and_inequalities_work_word_problems" },
          { id: "a2_equations_and_inequalities_distance_rate_time_word_problems", name: "Distance, rate, time word problems", type_id: "a2_equations_and_inequalities_distance_rate_time_word_problems" },
          { id: "a2_equations_and_inequalities_mixture_word_problems", name: "Mixture word problems", type_id: "a2_equations_and_inequalities_mixture_word_problems" },
          { id: "a2_equations_and_inequalities_absolute_value_equations", name: "Absolute value equations", type_id: "absolute_value_equations" },
          { id: "a2_equations_and_inequalities_multi_step_inequalities", name: "Multi-step inequalities", type_id: "multi_step_inequalities" },
          { id: "a2_equations_and_inequalities_compound_inequalities", name: "Compound inequalities", type_id: "compound_inequalities" },
          { id: "a2_equations_and_inequalities_absolute_value_inequalities", name: "Absolute value inequalities", type_id: "absolute_value_inequalities" },
        ],
      },
      {
        id: "relations_and_introduction_to_functions",
        name: "Relations and Introduction to Functions",
        topics: [
          { id: "a2_relations_and_introduction_to_functions_discrete_relations", name: "Discrete relations", type_id: "discrete_relations" },
          { id: "a2_relations_and_introduction_to_functions_continuous_relations", name: "Continuous relations", type_id: "continuous_relations" },
          { id: "a2_relations_and_introduction_to_functions_evaluating_and_graphing_functions", name: "Evaluating and graphing functions", type_id: "evaluating_graphing_functions" },
        ],
      },
      {
        id: "linear_relations_and_functions",
        name: "Linear Relations and Functions",
        topics: [
          { id: "a2_linear_relations_and_functions_graphing_linear_equations", name: "Graphing linear equations", type_id: "a2_linear_relations_and_functions_graphing_linear_equations" },
          { id: "a2_linear_relations_and_functions_writing_linear_equations", name: "Writing linear equations", type_id: "writing_linear_equations" },
          { id: "a2_linear_relations_and_functions_graphing_absolute_value_equations", name: "Graphing absolute value equations", type_id: "a2_linear_relations_and_functions_graphing_absolute_value_equations" },
          { id: "a2_linear_relations_and_functions_graphing_linear_inequalities", name: "Graphing linear inequalities", type_id: "a2_linear_relations_and_functions_graphing_linear_inequalities" },
        ],
      },
      {
        id: "direct_and_inverse_variation",
        name: "Direct and Inverse Variation",
        topics: [
          { id: "a2_direct_and_inverse_variation_direct_and_inverse_variation", name: "Direct and inverse variation", type_id: "direct_inverse_variation" },
        ],
      },
      {
        id: "systems_of_equations_and_inequalities",
        name: "Systems of Equations and Inequalities",
        topics: [
          { id: "a2_systems_of_equations_and_inequalities_graphing_systems_of_linear_inequalities", name: "Graphing systems of linear inequalities", type_id: "a2_systems_of_equations_and_inequalities_graphing_systems_of_linear_inequalities" },
          { id: "a2_systems_of_equations_and_inequalities_solving_systems_by_graphing_2_variables", name: "Solving systems by graphing (2 variables)", type_id: "a2_systems_of_equations_and_inequalities_solving_systems_by_graphing_2_variables" },
          { id: "a2_systems_of_equations_and_inequalities_solving_systems_by_elimination_2_variables", name: "Solving systems by elimination (2 variables)", type_id: "systems_elimination" },
          { id: "a2_systems_of_equations_and_inequalities_solving_systems_by_substitution_2_variables", name: "Solving systems by substitution (2 variables)", type_id: "systems_substitution" },
          { id: "a2_systems_of_equations_and_inequalities_systems_of_equations_word_problems_2_variables", name: "Systems of equations word problems (2 variables)", type_id: "a2_systems_of_equations_and_inequalities_systems_of_equations_word_problems_2_variables" },
          { id: "a2_systems_of_equations_and_inequalities_points_in_three_dimensions", name: "Points in three dimensions" },
          { id: "a2_systems_of_equations_and_inequalities_planes", name: "Planes" },
          { id: "a2_systems_of_equations_and_inequalities_solving_systems_with_three_variables", name: "Solving systems with three variables" },
        ],
      },
      {
        id: "matrices",
        name: "Matrices",
        topics: [
          { id: "a2_matrices_operations", name: "Operations", type_id: "a2_matrices_operations" },
          { id: "a2_matrices_determinants", name: "Determinants", type_id: "a2_matrices_determinants" },
          { id: "a2_matrices_inverses", name: "Inverses", type_id: "pc_inverses" },
          { id: "a2_matrices_cramers_rule", name: "Cramer's Rule" },
          { id: "a2_matrices_equations", name: "Equations", type_id: "a2_matrices_equations" },
          { id: "a2_matrices_geometric_transformations", name: "Geometric transformations" },
        ],
      },
      {
        id: "complex_numbers",
        name: "Complex Numbers",
        topics: [
          { id: "a2_complex_numbers_operations", name: "Operations", type_id: "a2_complex_numbers_operations" },
          { id: "a2_complex_numbers_graphing", name: "Graphing", type_id: "a2_complex_numbers_graphing" },
          { id: "a2_complex_numbers_absolute_value", name: "Absolute value", type_id: "a2_complex_numbers_absolute_value" },
          { id: "a2_complex_numbers_rationalizing_denominators", name: "Rationalizing denominators" },
        ],
      },
      {
        id: "quadratic_functions_and_inequalities",
        name: "Quadratic Functions and Inequalities",
        topics: [
          { id: "a2_quadratic_functions_and_inequalities_graphing_quadratic_functions", name: "Graphing quadratic functions", type_id: "a2_quadratic_functions_and_inequalities_graphing_quadratic_functions" },
          { id: "a2_quadratic_functions_and_inequalities_graphing_quadratic_inequalities", name: "Graphing quadratic inequalities", type_id: "a2_quadratic_functions_and_inequalities_graphing_quadratic_inequalities" },
          { id: "a2_quadratic_functions_and_inequalities_factoring_quadratic_expressions", name: "Factoring quadratic expressions", type_id: "quadratic_factoring" },
          { id: "a2_quadratic_functions_and_inequalities_factoring_special_case_quadratic_expressions", name: "Factoring special case quadratic expressions", type_id: "a2_quadratic_functions_and_inequalities_factoring_special_case_quadratic_expressions" },
          { id: "a2_quadratic_functions_and_inequalities_solving_equations_by_taking_square_roots", name: "Solving equations by taking square roots", type_id: "quadratic_square_roots" },
          { id: "a2_quadratic_functions_and_inequalities_solving_equations_by_factoring", name: "Solving equations by factoring", type_id: "quadratic_factoring_equations" },
          { id: "a2_quadratic_functions_and_inequalities_completing_the_square", name: "Completing the square", type_id: "a2_quadratic_functions_and_inequalities_completing_the_square" },
          { id: "a2_quadratic_functions_and_inequalities_solving_equations_by_completing_the_square", name: "Solving equations by completing the square", type_id: "quadratic_completing_square_solve" },
          { id: "a2_quadratic_functions_and_inequalities_solving_equations_with_the_quadratic_formula", name: "Solving equations with the Quadratic Formula", type_id: "quadratic_formula" },
          { id: "a2_quadratic_functions_and_inequalities_the_discriminant", name: "The discriminant", type_id: "a2_quadratic_functions_and_inequalities_the_discriminant" },
        ],
      },
      {
        id: "polynomial_functions",
        name: "Polynomial Functions",
        topics: [
          { id: "a2_polynomial_functions_naming", name: "Naming", type_id: "polynomial_naming" },
          { id: "a2_polynomial_functions_adding_and_subtracting", name: "Adding and subtracting", type_id: "polynomial_add_subtract" },
          { id: "a2_polynomial_functions_multiplying", name: "Multiplying", type_id: "polynomial_multiply" },
          { id: "a2_polynomial_functions_multiplying_special_cases", name: "Multiplying special cases", type_id: "polynomial_multiply_special" },
          { id: "a2_polynomial_functions_the_binomial_theorem", name: "The Binomial Theorem" },
          { id: "a2_polynomial_functions_dividing", name: "Dividing", type_id: "polynomial_long_division" },
          { id: "a2_polynomial_functions_factoring_by_grouping", name: "Factoring by grouping", type_id: "polynomial_factoring_grouping" },
          { id: "a2_polynomial_functions_factoring_sum_difference_of_cubes", name: "Factoring a sum/difference of cubes", type_id: "a2_polynomial_functions_factoring_sum_difference_of_cubes" },
          { id: "a2_polynomial_functions_factoring_quadratic_form", name: "Factoring quadratic form", type_id: "a2_polynomial_functions_factoring_quadratic_form" },
          { id: "a2_polynomial_functions_factoring_all_techniques", name: "Factoring all techniques", type_id: "a2_polynomial_functions_factoring_all_techniques" },
          { id: "a2_polynomial_functions_the_remainder_theorem", name: "The Remainder Theorem" },
          { id: "a2_polynomial_functions_writing_functions", name: "Writing functions" },
          { id: "a2_polynomial_functions_conjugate_roots_and_factoring", name: "Conjugate roots & factoring", type_id: "a2_polynomial_functions_conjugate_roots_and_factoring" },
          { id: "a2_polynomial_functions_conjugate_roots_and_writing_functions", name: "Conjugate roots & writing functions" },
          { id: "a2_polynomial_functions_descartes_rule_of_signs", name: "Descartes' Rule of Signs" },
          { id: "a2_polynomial_functions_rational_zero_root_theorem", name: "Rational Zero/Root Theorem" },
          { id: "a2_polynomial_functions_fundamental_theorem_of_algebra", name: "Fundamental Theorem of Algebra" },
          { id: "a2_polynomial_functions_solving_polynomial_equations", name: "Solving polynomial equations", type_id: "a2_polynomial_functions_solving_polynomial_equations" },
          { id: "a2_polynomial_functions_end_behavior_and_general_graph_shape", name: "End behavior and general graph shape" },
          { id: "a2_polynomial_functions_graphing", name: "Graphing", type_id: "a2_polynomial_functions_graphing" },
        ],
      },
      {
        id: "general_functions",
        name: "General Functions",
        topics: [
          { id: "a2_general_functions_evaluating", name: "Evaluating", type_id: "a2_general_functions_evaluating" },
          { id: "a2_general_functions_operations", name: "Operations", type_id: "a2_general_functions_operations" },
          { id: "a2_general_functions_inverses", name: "Inverses", type_id: "a2_general_functions_inverses" },
        ],
      },
      {
        id: "radical_functions_and_rational_exponents",
        name: "Radical Functions and Rational Exponents",
        topics: [
          { id: "a2_radical_functions_and_rational_exponents_simplifying_radicals", name: "Simplifying radicals", type_id: "radical_simplification" },
          { id: "a2_radical_functions_and_rational_exponents_adding_and_subtracting_radical_expressions", name: "Adding and subtracting radical expressions", type_id: "radical_add_subtract" },
          { id: "a2_radical_functions_and_rational_exponents_multiplying_radical_expressions", name: "Multiplying radical expressions", type_id: "radical_multiply" },
          { id: "a2_radical_functions_and_rational_exponents_dividing_radical_expressions", name: "Dividing radical expressions", type_id: "radical_divide" },
          { id: "a2_radical_functions_and_rational_exponents_connecting_radical_expressions_and_rational_exponents", name: "Connecting radical expressions and rational exponents", type_id: "a2_radical_functions_and_rational_exponents_connecting_radical_expressions_and_rational_exponents" },
          { id: "a2_radical_functions_and_rational_exponents_evaluating_rational_exponent_expressions", name: "Evaluating rational exponent expressions" },
          { id: "a2_radical_functions_and_rational_exponents_the_properties_of_exponents", name: "The properties of exponents", type_id: "a2_radical_functions_and_rational_exponents_the_properties_of_exponents" },
          { id: "a2_radical_functions_and_rational_exponents_radical_equations", name: "Radical equations", type_id: "radical_equations" },
          { id: "a2_radical_functions_and_rational_exponents_rational_exponent_equations", name: "Rational exponent equations" },
          { id: "a2_radical_functions_and_rational_exponents_graphing_radical_equations", name: "Graphing radical equations", type_id: "a2_radical_functions_and_rational_exponents_graphing_radical_equations" },
          { id: "a2_radical_functions_and_rational_exponents_domain_and_range_of_radical_functions", name: "Domain and range of radical functions" },
        ],
      },
      {
        id: "conic_sections",
        name: "Conic Sections",
        topics: [
          { id: "a2_conic_sections_parabolas_graphing_and_properties", name: "Parabolas graphing & properties", type_id: "a2_conic_sections_parabolas_graphing_and_properties" },
          { id: "a2_conic_sections_parabolas_writing_equations", name: "Parabolas writing equations", type_id: "a2_conic_sections_parabolas_writing_equations" },
          { id: "a2_conic_sections_circles_graphing_and_properties", name: "Circles graphing & properties", type_id: "a2_conic_sections_circles_graphing_and_properties" },
          { id: "a2_conic_sections_circles_writing_equations", name: "Circles writing equations", type_id: "a2_conic_sections_circles_writing_equations" },
          { id: "a2_conic_sections_ellipses_graphing_and_properties", name: "Ellipses graphing & properties", type_id: "a2_conic_sections_ellipses_graphing_and_properties" },
          { id: "a2_conic_sections_ellipses_writing_equations", name: "Ellipses writing equations", type_id: "a2_conic_sections_ellipses_writing_equations" },
          { id: "a2_conic_sections_hyperbolas_graphing_and_properties", name: "Hyperbolas graphing & properties", type_id: "a2_conic_sections_hyperbolas_graphing_and_properties" },
          { id: "a2_conic_sections_hyperbolas_writing_equations", name: "Hyperbolas writing equations", type_id: "a2_conic_sections_hyperbolas_writing_equations" },
          { id: "a2_conic_sections_classifying", name: "Classifying", type_id: "a2_conic_sections_classifying" },
          { id: "a2_conic_sections_systems_of_quadratic_equations", name: "Systems of quadratic equations" },
        ],
      },
      {
        id: "rational_expressions",
        name: "Rational Expressions",
        topics: [
          { id: "a2_rational_expressions_graphing", name: "Graphing", type_id: "a2_rational_expressions_graphing" },
          { id: "a2_rational_expressions_simplifying", name: "Simplifying", type_id: "rational_simplification" },
          { id: "a2_rational_expressions_multiplying_and_dividing", name: "Multiplying and dividing", type_id: "rational_expression_multiply_divide" },
          { id: "a2_rational_expressions_adding_and_subtracting", name: "Adding and subtracting", type_id: "rational_expression_simplification" },
          { id: "a2_rational_expressions_complex_fractions", name: "Complex fractions", type_id: "a2_rational_expressions_complex_fractions" },
          { id: "a2_rational_expressions_equations", name: "Equations" },
        ],
      },
      {
        id: "exponential_and_logarithmic_expressions",
        name: "Exponential and Logarithmic Expressions",
        topics: [
          { id: "a2_exponential_and_logarithmic_expressions_graphing_exponential_functions", name: "Graphing exponential functions", type_id: "a2_exponential_and_logarithmic_expressions_graphing_exponential_functions" },
          { id: "a2_exponential_and_logarithmic_expressions_exponential_equations_not_requiring_logarithms", name: "Exponential equations not requiring logarithms", type_id: "a2_exponential_and_logarithmic_expressions_exponential_equations_not_requiring_logarithms" },
          { id: "a2_exponential_and_logarithmic_expressions_exponents_and_logarithms", name: "Exponents and logarithms" },
          { id: "a2_exponential_and_logarithmic_expressions_evaluating_logarithms", name: "Evaluating logarithms", type_id: "a2_exponential_and_logarithmic_expressions_evaluating_logarithms" },
          { id: "a2_exponential_and_logarithmic_expressions_logarithms_and_exponents_as_inverses", name: "Logarithms and exponents as inverses" },
          { id: "a2_exponential_and_logarithmic_expressions_properties_of_logarithms", name: "Properties of logarithms", type_id: "a2_exponential_and_logarithmic_expressions_properties_of_logarithms" },
          { id: "a2_exponential_and_logarithmic_expressions_writing_logs_in_terms_of_others", name: "Writing logs in terms of others" },
          { id: "a2_exponential_and_logarithmic_expressions_exponential_equations_requiring_logarithms", name: "Exponential equations requiring logarithms", type_id: "a2_exponential_and_logarithmic_expressions_exponential_equations_requiring_logarithms" },
          { id: "a2_exponential_and_logarithmic_expressions_inverses_of_exponential_and_logarithmic_functions", name: "Inverses of exponential and logarithmic functions" },
          { id: "a2_exponential_and_logarithmic_expressions_logarithmic_equations_simple", name: "Logarithmic equations, simple", type_id: "a2_exponential_and_logarithmic_expressions_logarithmic_equations_simple" },
          { id: "a2_exponential_and_logarithmic_expressions_logarithmic_equations_hard", name: "Logarithmic equations, hard", type_id: "a2_exponential_and_logarithmic_expressions_logarithmic_equations_hard" },
          { id: "a2_exponential_and_logarithmic_expressions_graphing_logarithmic_functions", name: "Graphing logarithmic functions", type_id: "a2_exponential_and_logarithmic_expressions_graphing_logarithmic_functions" },
          { id: "a2_exponential_and_logarithmic_expressions_discrete_exponential_growth_and_decay_word_problems", name: "Discrete exponential growth and decay word problems", type_id: "exponential_growth_decay" },
          { id: "a2_exponential_and_logarithmic_expressions_continuous_exponential_growth_and_decay_word_problems", name: "Continuous exponential growth and decay word problems", type_id: "a2_exponential_and_logarithmic_expressions_continuous_exponential_growth_and_decay_word_problems" },
        ],
      },
      {
        id: "sequences_and_series",
        name: "Sequences and Series",
        topics: [
          { id: "a2_sequences_and_series_general_sequences", name: "General sequences" },
          { id: "a2_sequences_and_series_arithmetic_sequences", name: "Arithmetic sequences", type_id: "a2_sequences_and_series_arithmetic_sequences" },
          { id: "a2_sequences_and_series_geometric_sequences", name: "Geometric sequences", type_id: "a2_sequences_and_series_geometric_sequences" },
          { id: "a2_sequences_and_series_arithmetic_and_geometric_mean", name: "Arithmetic and geometric mean", type_id: "a2_sequences_and_series_arithmetic_and_geometric_mean" },
          { id: "a2_sequences_and_series_general_series", name: "General series" },
          { id: "a2_sequences_and_series_arithmetic_series", name: "Arithmetic series", type_id: "a2_sequences_and_series_arithmetic_series" },
          { id: "a2_sequences_and_series_geometric_series", name: "Geometric series", type_id: "a2_sequences_and_series_geometric_series" },
        ],
      },
      {
        id: "trigonometry",
        name: "Trigonometry",
        topics: [
          { id: "a2_trigonometry_angles_and_angle_measure", name: "Angles and angle measure" },
          { id: "a2_trigonometry_radians_and_degrees", name: "Radians and degrees", type_id: "a2_trigonometry_radians_and_degrees" },
          { id: "a2_trigonometry_degrees_and_degrees_minutes_seconds", name: "Degrees and degrees-minutes-seconds" },
          { id: "a2_trigonometry_coterminal_angles", name: "Coterminal angles" },
          { id: "a2_trigonometry_arc_length_and_sector_area", name: "Arc length and sector area" },
          { id: "a2_trigonometry_right_triangle_trig_finding_ratios", name: "Right triangle trig, finding ratios", type_id: "a2_trigonometry_right_triangle_trig_finding_ratios" },
          { id: "a2_trigonometry_right_triangle_trig_finding_angle_measures", name: "Right triangle trig, finding angle measures", type_id: "a2_trigonometry_right_triangle_trig_finding_angle_measures" },
          { id: "a2_trigonometry_right_triangle_trig_angles_and_sides", name: "Right triangle trig, angles and sides", type_id: "a2_trigonometry_right_triangle_trig_angles_and_sides" },
          { id: "a2_trigonometry_trig_functions_of_any_angle", name: "Trig functions of any angle", type_id: "a2_trigonometry_trig_functions_of_any_angle" },
          { id: "a2_trigonometry_the_law_of_sines", name: "Law of Sines" },
          { id: "a2_trigonometry_the_law_of_cosines", name: "Law of Cosines" },
          { id: "a2_trigonometry_area_and_laws_of_sines_and_cosines", name: "Area and Laws" },
          { id: "a2_trigonometry_graphing_trig_functions", name: "Graphing trig functions" },
          { id: "a2_trigonometry_angle_sum_difference_identities", name: "Angle sum/difference identities", type_id: "a2_trigonometry_angle_sum_difference_identities" },
          { id: "a2_trigonometry_double_angle_half_angle_identities", name: "Double-angle/half-angle identities", type_id: "a2_trigonometry_double_angle_half_angle_identities" },
          { id: "a2_trigonometry_equations", name: "Equations", type_id: "a2_trigonometry_equations" },
        ],
      },
      {
        id: "probability_and_statistics",
        name: "Probability and Statistics",
        topics: [
          { id: "a2_probability_and_statistics_sample_spaces_and_the_fundamental_counting_principle", name: "Sample spaces and the Fundamental Counting Principle", type_id: "a2_probability_and_statistics_sample_spaces_and_the_fundamental_counting_principle" },
          { id: "a2_probability_and_statistics_probability_of_independent_and_dependent_events_word_problems", name: "Probability of independent and dependent events, word problems", type_id: "a2_probability_and_statistics_probability_of_independent_and_dependent_events_word_problems" },
          { id: "a2_probability_and_statistics_probability_of_independent_and_dependent_events", name: "Probability of independent and dependent events", type_id: "a2_probability_and_statistics_probability_of_independent_and_dependent_events" },
          { id: "a2_probability_and_statistics_probability_of_mutually_exclusive_events_word_problems", name: "Probability of mutually exclusive events, word problems", type_id: "a2_probability_and_statistics_probability_of_mutually_exclusive_events_word_problems" },
          { id: "a2_probability_and_statistics_probability_of_mutually_exclusive_events", name: "Probability of mutually exclusive events", type_id: "a2_probability_and_statistics_probability_of_mutually_exclusive_events" },
          { id: "a2_probability_and_statistics_permutations", name: "Permutations", type_id: "a2_probability_and_statistics_permutations" },
          { id: "a2_probability_and_statistics_combinations", name: "Combinations", type_id: "a2_probability_and_statistics_combinations" },
          { id: "a2_probability_and_statistics_permutations_vs_combinations", name: "Permutations vs combinations", type_id: "a2_probability_and_statistics_permutations_vs_combinations" },
          { id: "a2_probability_and_statistics_probability_with_permutations_and_combinations", name: "Probability with permutations and combinations", type_id: "a2_probability_and_statistics_probability_with_permutations_and_combinations" },
        ],
      },
    ],
  },
  {
    id: "geometry",
    name: "Geometry",
    topics: [
      {
        id: "review_of_algebra",
        name: "Review of Algebra",
        topics: [
          { id: "geo_review_multi_step_equations", name: "Multi-step equations", type_id: "multi_step_equations" },
          { id: "geo_review_simplifying_square_roots", name: "Simplifying square roots", type_id: "geo_review_simplifying_square_roots" },
          {
            id: "geo_review_adding_and_subtracting_square_roots",
            name: "Adding and subtracting square roots", type_id: "geo_review_adding_and_subtracting_square_roots" },
          { id: "geo_review_multiplying_square_roots", name: "Multiplying square roots", type_id: "geo_review_multiplying_square_roots" },
          { id: "geo_review_dividing_square_roots", name: "Dividing square roots", type_id: "geo_review_dividing_square_roots" },
        ],
      },
      {
        id: "basics_of_geometry",
        name: "Basics of Geometry",
        topics: [
          {
            id: "geo_basics_line_segments_and_their_measures",
            name: "Line segments and their measures", type_id: "geo_basics_line_segments_and_their_measures" },
          { id: "geo_basics_segment_addition_postulate", name: "Segment Addition Postulate" },
          { id: "geo_basics_angles_and_their_measures", name: "Angles and their measures", type_id: "geo_basics_angles_and_their_measures" },
          { id: "geo_basics_classifying_angles", name: "Classifying angles", type_id: "geo_basics_classifying_angles" },
          { id: "geo_basics_basic_angle_terminology", name: "Basic angle terminology" },
          { id: "geo_basics_angle_addition_postulate", name: "Angle Addition Postulate" },
          { id: "geo_basics_angle_relationships", name: "Angle relationships" },
          {
            id: "geo_basics_geometric_diagrams_and_notation",
            name: "Geometric diagrams and notation",
          },
        ],
      },
      {
        id: "parallel_lines_and_the_coordinate_plane",
        name: "Parallel Lines and the Coordinate Plane",
        topics: [
          {
            id: "geo_parallel_parallel_lines_and_transversals",
            name: "Parallel lines and transversals",
          },
          {
            id: "geo_parallel_points_of_the_coordinate_plane",
            name: "Points of the coordinate plane", type_id: "geo_parallel_points_of_the_coordinate_plane" },
          { id: "radical_midpoint_formula", name: "The Midpoint Formula", type_id: "radical_midpoint_formula" },
          { id: "radical_distance_formula", name: "The Distance Formula", type_id: "radical_distance_formula" },
          { id: "geo_parallel_slope_and_lines", name: "Slope and lines", type_id: "geo_parallel_slope_and_lines" },
          { id: "geo_parallel_graphing_linear_equations", name: "Graphing linear equations", type_id: "geo_parallel_graphing_linear_equations" },
          { id: "geo_parallel_writing_linear_equations", name: "Writing linear equations", type_id: "writing_linear_equations" },
        ],
      },
      {
        id: "congruent_triangles",
        name: "Congruent Triangles",
        topics: [
          { id: "geo_congruent_classifying_triangles", name: "Classifying triangles" },
          { id: "geo_congruent_triangle_angle_sum", name: "Triangle angle sum", type_id: "geo_congruent_triangle_angle_sum" },
          { id: "geo_congruent_exterior_angle_theorem", name: "Exterior Angle Theorem" },
          { id: "geo_congruent_triangles_and_congruence", name: "Triangles and congruence" },
          { id: "geo_congruent_proving_triangles_congruent", name: "Proving triangles congruent" },
          {
            id: "geo_congruent_isosceles_and_equilateral_triangles",
            name: "Isosceles and equilateral triangles",
          },
        ],
      },
      {
        id: "properties_of_triangles",
        name: "Properties of Triangles",
        topics: [
          { id: "geo_properties_midsegment", name: "Midsegment" },
          { id: "geo_properties_angle_bisectors", name: "Angle bisectors" },
          { id: "geo_properties_medians", name: "Medians" },
          { id: "geo_properties_centroid", name: "Centroid" },
          {
            id: "geo_properties_triangle_inequality_theorem",
            name: "Triangle Inequality Theorem",
          },
          {
            id: "geo_properties_inequalities_in_one_triangle",
            name: "Inequalities in one triangle",
          },
        ],
      },
      {
        id: "quadrilaterals_and_polygons",
        name: "Quadrilaterals and Polygons",
        topics: [
          { id: "geo_quadrilaterals_classifying", name: "Classifying" },
          { id: "geo_quadrilaterals_angles", name: "Angles" },
          { id: "geo_quadrilaterals_parallelograms", name: "Parallelograms" },
          { id: "geo_quadrilaterals_trapezoids", name: "Trapezoids" },
          { id: "geo_quadrilaterals_rhombuses", name: "Rhombuses" },
          { id: "geo_quadrilaterals_kites", name: "Kites" },
          {
            id: "geo_quadrilaterals_area_of_triangles_and_quadrilaterals",
            name: "Area of triangles and quadrilaterals", type_id: "geo_quadrilaterals_area_of_triangles_and_quadrilaterals" },
          { id: "geo_quadrilaterals_polygon_basics", name: "Polygon basics" },
          { id: "geo_quadrilaterals_area_of_regular_polygons", name: "Area of regular polygons" },
        ],
      },
      {
        id: "similarity",
        name: "Similarity",
        topics: [
          { id: "solving_proportions", name: "Solving proportions", type_id: "solving_proportions" },
          { id: "geo_similarity_similar_polygons", name: "Similar polygons" },
          { id: "geo_similarity_similar_triangles", name: "Similar triangles", type_id: "geo_similarity_similar_triangles" },
          { id: "geo_similarity_similar_right_triangles", name: "Similar right triangles" },
          {
            id: "geo_similarity_proportional_parts_in_triangles_and_parallel_lines",
            name: "Proportional parts in triangles and parallel lines",
          },
        ],
      },
      {
        id: "right_triangles",
        name: "Right Triangles",
        topics: [
          { id: "pythagorean_theorem", name: "The Pythagorean Theorem", type_id: "pythagorean_theorem" },
          {
            id: "geo_right_multi_step_pythagorean_theorem_problems",
            name: "Multi-step Pythagorean Theorem problems",
          },
          { id: "geo_right_special_right_triangles", name: "Special right triangles", type_id: "geo_right_special_right_triangles" },
          {
            id: "geo_right_multi_step_special_right_triangle_problems",
            name: "Multi-step special right triangle problems",
          },
        ],
      },
      {
        id: "trigonometry",
        name: "Trigonometry",
        topics: [
          { id: "geo_trig_finding_trig_ratios", name: "Finding trig. ratios", type_id: "geo_trig_finding_trig_ratios" },
          { id: "geo_trig_finding_angle_measures", name: "Finding angle measures", type_id: "geo_trig_finding_angle_measures" },
          { id: "geo_trig_solving_right_triangles", name: "Solving right triangles", type_id: "geo_trig_solving_right_triangles" },
          { id: "geo_trig_multi_step_trig_problems", name: "Multi-step trig. problems", type_id: "geo_trig_multi_step_trig_problems" },
          {
            id: "geo_trig_rhombuses_and_kites_with_right_triangles",
            name: "Rhombuses and kites with right triangles",
            type_id: "geo_trig_rhombuses_and_kites_with_right_triangles",
          },
          { id: "geo_trig_trigonometry_and_area", name: "Trigonometry and area", type_id: "geo_trig_trigonometry_and_area" },
        ],
      },
      {
        id: "surface_area_and_volume",
        name: "Surface Area and Volume",
        topics: [
          {
            id: "geo_solid_figures_identifying_volume_and_area",
            name: "Solid figures: identifying, volume, and area",
          },
          { id: "geo_nets_of_solids", name: "Nets of solids" },
          { id: "geo_similar_solids", name: "Similar solids" },
        ],
      },
      {
        id: "circles",
        name: "Circles",
        topics: [
          { id: "geo_circles_naming_arcs_and_central_angles", name: "Naming arcs and central angles" },
          {
            id: "geo_circles_measures_of_arcs_and_central_angles",
            name: "Measures of arcs and central angles",
          },
          { id: "geo_circles_arcs_and_chords", name: "Arcs and chords" },
          { id: "geo_circles_circumference_and_area", name: "Circumference and area", type_id: "geo_circles_circumference_and_area" },
          { id: "geo_circles_arc_length_and_sector_area", name: "Arc length and sector area" },
          { id: "geo_circles_inscribed_angles", name: "Inscribed angles" },
          { id: "geo_circles_tangents", name: "Tangents" },
          { id: "geo_circles_secant_and_tangent_angles", name: "Secant and tangent angles" },
          { id: "geo_circles_segment_measures", name: "Segment measures" },
          { id: "geo_circles_using_equations_of_circles", name: "Using equations of circles" },
          { id: "geo_circles_writing_equations_of_circles", name: "Writing equations of circles" },
        ],
      },
      {
        id: "transformations",
        name: "Transformations",
        topics: [
          {
            id: "geo_transformations_translations_rotations_reflections_and_dilations",
            name: "Translations, rotations, reflections, and dilations",
          },
        ],
      },
      {
        id: "probability_and_statistics",
        name: "Probability and Statistics",
        topics: [
          {
            id: "geo_probability_sample_spaces_and_fundamental_counting_principle",
            name: "Sample spaces and the Fundamental Counting Principle", type_id: "geo_probability_sample_spaces_and_fundamental_counting_principle" },
          {
            id: "geo_probability_independent_and_dependent_events_word_problems",
            name: "Probability of independent and dependent events, word problems",
          },
          {
            id: "geo_probability_independent_and_dependent_events",
            name: "Probability of independent and dependent events", type_id: "geo_probability_independent_and_dependent_events" },
          {
            id: "geo_probability_mutually_exclusive_events_word_problems",
            name: "Probability of mutually exclusive events, word problems",
          },
          {
            id: "geo_probability_mutually_exclusive_events",
            name: "Probability of mutually exclusive events", type_id: "geo_probability_mutually_exclusive_events" },
          { id: "geo_probability_permutations", name: "Permutations", type_id: "geo_probability_permutations" },
          { id: "geo_probability_combinations", name: "Combinations", type_id: "geo_probability_combinations" },
          { id: "geo_probability_permutations_vs_combinations", name: "Permutations vs combinations", type_id: "geo_probability_permutations_vs_combinations" },
          {
            id: "geo_probability_with_permutations_and_combinations",
            name: "Probability with permutations and combinations",
          },
        ],
      },
      {
        id: "constructions",
        name: "Constructions",
        topics: [
          { id: "geo_constructions_line_segments", name: "Line segments" },
          { id: "geo_constructions_perpendicular_segments", name: "Perpendicular segments" },
          { id: "geo_constructions_angles", name: "Angles" },
          { id: "geo_constructions_triangles", name: "Triangles" },
          { id: "geo_constructions_medians_of_a_triangle", name: "Medians of a triangle" },
          { id: "geo_constructions_altitudes_of_a_triangle", name: "Altitudes of a triangle" },
          { id: "geo_constructions_angle_bisectors", name: "Angle bisectors" },
          { id: "geo_constructions_circles", name: "Circles" },
        ],
      },
    ],
  },
  {
    id: "precalculus",
    name: "Precalculus",
    topics: [
      {
        id: "functions",
        name: "Functions",
        topics: [
          { id: "pc_continuity", name: "Continuity" },
          { id: "pc_extrema_intervals_of_increase_and_decrease", name: "Extrema, intervals of increase and decrease" },
          { id: "pc_power_functions", name: "Power functions" },
          { id: "pc_average_rates_of_change", name: "Average rates of change" },
          { id: "pc_transformations_of_graphs", name: "Transformations of graphs", type_id: "pc_transformations_of_graphs" },
          { id: "pc_piecewise_functions", name: "Piecewise functions" },
          { id: "pc_functions_operations", name: "Operations", type_id: "pc_functions_operations" },
          { id: "pc_inverses", name: "Inverses", type_id: "pc_inverses" },
        ],
      },
      {
        id: "power_polynomial_and_rational_functions",
        name: "Power, Polynomial, and Rational Functions",
        topics: [
          { id: "pc_polynomial_graphs_real_zeros_and_end_behavior", name: "Graphs, real zeros, and end behavior of polynomial functions", type_id: "pc_polynomial_graphs_real_zeros_and_end_behavior" },
          { id: "pc_dividing_polynomial_functions", name: "Dividing polynomial functions", type_id: "pc_dividing_polynomial_functions" },
          { id: "pc_remainder_theorem_and_bounds_of_real_zeros", name: "The Remainder Theorem and bounds of real zeros" },
          { id: "pc_writing_polynomial_functions_and_conjugate_roots", name: "Writing polynomial functions and conjugate roots" },
          { id: "pc_complex_zeros_and_fundamental_theorem_of_algebra", name: "Complex zeros and The Fundamental Theorem of Algebra" },
          { id: "pc_graphs_of_rational_functions", name: "Graphs of rational functions", type_id: "pc_graphs_of_rational_functions" },
          { id: "pc_rational_equations", name: "Rational equations" },
          { id: "pc_polynomial_inequalities", name: "Polynomial inequalities" },
          { id: "pc_rational_inequalities", name: "Rational inequalities" },
        ],
      },
      {
        id: "exponential_and_logarithmic_expressions",
        name: "Exponential and Logarithmic Expressions",
        topics: [
          { id: "pc_graphing_exponential_functions", name: "Graphing exponential functions", type_id: "pc_graphing_exponential_functions" },
          { id: "pc_exponential_equations_not_requiring_logarithms", name: "Exponential equations not requiring logarithms", type_id: "pc_exponential_equations_not_requiring_logarithms" },
          { id: "pc_exponents_and_logarithms", name: "Exponents and logarithms" },
          { id: "pc_evaluating_logarithms", name: "Evaluating logarithms", type_id: "pc_evaluating_logarithms" },
          { id: "pc_logarithms_and_exponents_as_inverses", name: "Logarithms and exponents as inverses" },
          { id: "pc_properties_of_logarithms", name: "Properties of logarithms" },
          { id: "pc_writing_logs_in_terms_of_others", name: "Writing logs in terms of others", type_id: "pc_writing_logs_in_terms_of_others" },
          { id: "pc_exponential_equations_requiring_logarithms", name: "Exponential equations requiring logarithms", type_id: "pc_exponential_equations_requiring_logarithms" },
          { id: "pc_logarithmic_equations_simple", name: "Logarithmic equations, simple", type_id: "pc_logarithmic_equations_simple" },
          { id: "pc_logarithmic_equations_hard", name: "Logarithmic equations, hard" },
          { id: "pc_graphing_logarithmic_functions", name: "Graphing logarithmic functions" },
          { id: "pc_compound_interest", name: "Compound interest" },
        ],
      },
      {
        id: "trigonometry",
        name: "Trigonometry",
        topics: [
          { id: "pc_angles_and_angle_measure", name: "Angles and angle measure" },
          { id: "pc_radians_and_degrees", name: "Radians and degrees", type_id: "pc_radians_and_degrees" },
          { id: "pc_right_triangle_trig_finding_ratios", name: "Right triangle trig, finding ratios", type_id: "pc_right_triangle_trig_finding_ratios" },
          { id: "pc_right_triangle_trig_finding_angles_and_sides", name: "Right triangle trig, finding angles and sides", type_id: "pc_right_triangle_trig_finding_angles_and_sides" },
          { id: "pc_trig_functions_of_any_angle", name: "Trig functions of any angle", type_id: "pc_trig_functions_of_any_angle" },
          { id: "pc_graphing_trig_functions", name: "Graphing trig functions" },
          { id: "pc_simple_trig_equations", name: "Simple trig equations", type_id: "pc_simple_trig_equations" },
          { id: "pc_inverse_trig_functions", name: "Inverse trig functions" },
          { id: "pc_fundamental_identities", name: "Fundamental identities", type_id: "pc_fundamental_identities" },
          { id: "pc_equations_with_factoring_and_fundamental_identities", name: "Equations with factoring and fundamental identities" },
          { id: "pc_sum_and_difference_identities", name: "Sum and Difference Identities" },
          { id: "pc_multiple_angle_identities", name: "Multiple-Angle Identities" },
          { id: "pc_product_to_sum_identities", name: "Product-to-Sum Identities" },
          { id: "pc_equations_and_multiple_angle_identities", name: "Equations and Multiple-Angle Identities" },
          { id: "pc_law_of_sines", name: "The Law of Sines" },
          { id: "pc_law_of_cosines", name: "The Law of Cosines" },
          { id: "pc_area_and_laws_of_sines_and_cosines", name: "Area and Laws of Sines and Cosines" },
        ],
      },
      {
        id: "parametric_equations",
        name: "Parametric Equations",
        topics: [
          { id: "pc_parametric_equations", name: "Parametric equations" },
          { id: "pc_projectile_motion", name: "Projectile motion" },
        ],
      },
      {
        id: "polar_coordinates",
        name: "Polar Coordinates",
        topics: [
          { id: "pc_polar_coordinates", name: "Polar coordinates" },
          { id: "pc_graphs_of_polar_equations", name: "Graphs of polar equations" },
          { id: "pc_polar_and_rectangular_forms_of_equations", name: "Polar and rectangular forms of equations" },
          { id: "pc_polar_forms_of_conic_sections", name: "Polar forms of conic sections" },
          { id: "pc_complex_numbers_in_polar_form", name: "Complex numbers in polar form" },
        ],
      },
      {
        id: "vectors",
        name: "Vectors",
        topics: [
          { id: "pc_vectors_basics", name: "Basics" },
          { id: "pc_vectors_diagrams", name: "Diagrams" },
          { id: "pc_vectors_operations", name: "Operations", type_id: "pc_vectors_operations" },
          { id: "pc_dot_products", name: "Dot products" },
        ],
      },
      {
        id: "three_dimensional_vectors",
        name: "Three-Dimensional Vectors",
        topics: [
          { id: "pc_3d_points_in_three_dimensions", name: "Points in three dimensions" },
          { id: "pc_3d_vectors_basics", name: "Basics" },
          { id: "pc_3d_vectors_operations", name: "Operations", type_id: "pc_3d_vectors_operations" },
          { id: "pc_cross_products", name: "Cross products" },
        ],
      },
      {
        id: "matrices_and_systems",
        name: "Matrices and Systems",
        topics: [
          { id: "a2_matrices_operations", name: "Operations", type_id: "a2_matrices_operations" },
          { id: "a2_matrices_determinants", name: "Determinants", type_id: "a2_matrices_determinants" },
          { id: "a2_matrices_inverses", name: "Inverses", type_id: "pc_inverses" },
          { id: "a2_matrices_cramer_s_rule", name: "Cramer's Rule" },
          { id: "a2_matrices_equations", name: "Equations", type_id: "a2_matrices_equations" },
          { id: "pc_multivariable_linear_systems_and_row_operations", name: "Multivariable linear systems and row operations" },
          { id: "pc_partial_fraction_decomposition", name: "Partial fraction decomposition" },
        ],
      },
      {
        id: "conic_sections",
        name: "Conic Sections",
        topics: [
          { id: "pc_parabolas_graphing_and_properties", name: "Parabolas, graphing and properties", type_id: "pc_parabolas_graphing_and_properties" },
          { id: "pc_parabolas_writing_equations", name: "Parabolas, writing equations" },
          { id: "pc_circles_graphing_and_properties", name: "Circles, graphing and properties" },
          { id: "pc_circles_writing_equations", name: "Circles, writing equations" },
          { id: "pc_ellipses_graphing_and_properties", name: "Ellipses, graphing and properties" },
          { id: "pc_ellipses_writing_equations", name: "Ellipses, writing equations" },
          { id: "pc_hyperbolas_graphing_and_properties", name: "Hyperbolas, graphing and properties" },
          { id: "pc_hyperbolas_writing_equations", name: "Hyperbolas, writing equations" },
          { id: "pc_rotations_of_conic_sections", name: "Rotations of conic sections" },
        ],
      },
      {
        id: "discrete_mathematics",
        name: "Discrete Mathematics",
        topics: [
          { id: "pc_sample_spaces_and_fundamental_counting_principle", name: "Sample spaces and Fundamental Counting Principle", type_id: "pc_sample_spaces_and_fundamental_counting_principle" },
          { id: "a2_probability_and_statistics_permutations", name: "Permutations", type_id: "a2_probability_and_statistics_permutations" },
          { id: "a2_probability_and_statistics_combinations", name: "Combinations", type_id: "a2_probability_and_statistics_combinations" },
          { id: "pc_permutations_vs_combinations", name: "Permutations vs combinations" },
          { id: "pc_binomial_theorem", name: "The Binomial Theorem" },
          { id: "pc_mathematical_induction", name: "Mathematical induction" },
          { id: "pc_probability_independent_dependent_events_word_problems", name: "Probability: Independent/dependent events, word problems" },
          { id: "pc_probability_independent_dependent_events", name: "Probability: Independent/dependent events", type_id: "pc_probability_independent_dependent_events" },
          { id: "pc_probability_mutually_exclusive_word_problems", name: "Probability: Mutually exclusive, word problems" },
          { id: "pc_probability_mutually_exclusive", name: "Probability: Mutually exclusive", type_id: "pc_probability_mutually_exclusive" },
          { id: "pc_probability_with_permutations_and_combinations", name: "Probability: With permutations and combinations" },
        ],
      },
      {
        id: "sequences_and_series",
        name: "Sequences and Series",
        topics: [
          { id: "a2_sequences_and_series_general_sequences", name: "General sequences" },
          { id: "a2_sequences_and_series_arithmetic_sequences", name: "Arithmetic sequences", type_id: "a2_sequences_and_series_arithmetic_sequences" },
          { id: "a2_sequences_and_series_geometric_sequences", name: "Geometric sequences", type_id: "a2_sequences_and_series_geometric_sequences" },
          { id: "a2_sequences_and_series_arithmetic_and_geometric_mean", name: "Arithmetic and geometric mean", type_id: "a2_sequences_and_series_arithmetic_and_geometric_mean" },
          { id: "a2_sequences_and_series_general_series", name: "General series" },
          { id: "a2_sequences_and_series_arithmetic_series", name: "Arithmetic series", type_id: "a2_sequences_and_series_arithmetic_series" },
          { id: "a2_sequences_and_series_geometric_series", name: "Geometric series", type_id: "a2_sequences_and_series_geometric_series" },
          { id: "pc_power_series", name: "Power series" },
        ],
      },
      {
        id: "introduction_to_calculus",
        name: "Introduction to Calculus",
        topics: [
          { id: "pc_limits_by_direct_evaluation", name: "Limits by direct evaluation", type_id: "pc_limits_by_direct_evaluation" },
          { id: "pc_limits_at_kinks_and_jumps", name: "Limits at kinks and jumps" },
          { id: "pc_limits_at_removable_discontinuities", name: "Limits at removable discontinuities" },
          { id: "pc_limits_at_essential_discontinuities", name: "Limits at essential discontinuities" },
          { id: "pc_limits_at_infinity", name: "Limits at infinity" },
          { id: "pc_definition_of_the_derivative", name: "Definition of the derivative" },
          { id: "pc_instantaneous_rates_of_change", name: "Instantaneous rates of change" },
          { id: "pc_power_rule_for_differentiation", name: "Power rule for differentiation", type_id: "pc_power_rule_for_differentiation" },
          { id: "pc_motion_along_a_line", name: "Motion along a line" },
          { id: "pc_approximating_area_under_a_curve", name: "Approximating area under a curve" },
          { id: "pc_area_under_a_curve_by_limit_of_sums", name: "Area under a curve by limit of sums" },
          { id: "pc_indefinite_integrals", name: "Indefinite integrals", type_id: "pc_indefinite_integrals" },
        ],
      },
    ],
  },
  {
    id: "calculus",
    name: "Calculus",
    topics: [
      {
        id: "limits",
        name: "Limits",
        topics: [
          { id: "calc_limits_by_direct_evaluation", name: "By direct evaluation", type_id: "calc_limits_by_direct_evaluation" },
          { id: "calc_limits_at_jump_discontinuities_and_kinks", name: "At jump discontinuities and kinks" },
          { id: "calc_limits_at_removable_discontinuities", name: "At removable discontinuities" },
          { id: "calc_limits_at_essential_discontinuities", name: "At essential discontinuities" },
          { id: "calc_limits_at_infinity", name: "At infinity", type_id: "calc_limits_at_infinity" },
        ],
      },
      {
        id: "continuity",
        name: "Continuity",
        topics: [
          { id: "calc_continuity_determining_and_classifying", name: "Determining and classifying" },
        ],
      },
      {
        id: "differentiation",
        name: "Differentiation",
        topics: [
          { id: "calc_diff_average_rates_of_change", name: "Average rates of change" },
          { id: "calc_diff_definition_of_the_derivative", name: "Definition of the derivative" },
          { id: "calc_diff_instantaneous_rates_of_change", name: "Instantaneous rates of change" },
          { id: "calc_diff_power_rule", name: "Power Rule", type_id: "calc_diff_power_rule" },
          { id: "calc_diff_higher_order_derivatives", name: "Higher order derivatives" },
          { id: "calc_diff_product_rule", name: "Product Rule" },
          { id: "calc_diff_quotient_rule", name: "Quotient Rule" },
          { id: "calc_diff_chain_rule", name: "Chain Rule" },
          { id: "calc_diff_rules_using_tables", name: "Rules, using tables" },
          { id: "calc_diff_trigonometric", name: "Trigonometric" },
          { id: "calc_diff_inverse_trigonometric", name: "Inverse trigonometric" },
          { id: "calc_diff_natural_logarithms_and_exponentials", name: "Natural logarithms and exponentials" },
          { id: "calc_diff_other_base_logarithms_and_exponentials", name: "Other base logarithms and exponentials" },
          { id: "calc_diff_logarithmic", name: "Logarithmic" },
          { id: "calc_diff_implicit", name: "Implicit" },
          { id: "calc_diff_inverse_functions", name: "Inverse functions" },
        ],
      },
      {
        id: "applications_of_differentiation",
        name: "Applications of Differentiation",
        topics: [
          { id: "calc_app_diff_slope_tangent_and_normal_lines", name: "Slope, tangent, and normal lines" },
          { id: "calc_app_diff_rolles_theorem", name: "Rolle's Theorem" },
          { id: "calc_app_diff_mean_value_theorem", name: "Mean Value Theorem" },
          { id: "calc_app_diff_intervals_of_increase_and_decrease", name: "Intervals of increase and decrease" },
          { id: "calc_app_diff_intervals_of_concavity", name: "Intervals of concavity" },
          { id: "calc_app_diff_relative_extrema", name: "Relative extrema" },
          { id: "calc_app_diff_absolute_extrema", name: "Absolute extrema" },
          { id: "calc_app_diff_optimization", name: "Optimization" },
          { id: "calc_app_diff_curve_sketching", name: "Curve sketching" },
          { id: "calc_app_diff_graphical_comparison_of_f_f_prime_and_f_double_prime", name: "Graphical comparison of f, f', and f''" },
          { id: "calc_app_diff_motion_along_a_line", name: "Motion along a line" },
          { id: "calc_app_diff_related_rates", name: "Related rates" },
          { id: "calc_app_diff_differentials", name: "Differentials" },
          { id: "calc_app_diff_newtons_method", name: "Newton's Method" },
          { id: "calc_app_diff_limits_in_form_of_definition_of_derivative", name: "Limits in form of definition of derivative" },
          { id: "calc_app_diff_lhopitals_rule", name: "L'Hôpital's Rule" },
        ],
      },
      {
        id: "indefinite_integration",
        name: "Indefinite Integration",
        topics: [
          { id: "calc_indef_int_power_rule", name: "Power Rule", type_id: "calc_indef_int_power_rule" },
          { id: "calc_indef_int_logarithmic_rule_and_exponentials", name: "Logarithmic Rule and Exponentials" },
          { id: "calc_indef_int_trigonometric", name: "Trigonometric" },
          { id: "calc_indef_int_inverse_trigonometric", name: "Inverse trigonometric" },
          { id: "calc_indef_int_power_rule_with_substitution", name: "Power rule with substitution" },
          { id: "calc_indef_int_logarithmic_rule_and_exponentials_with_substitution", name: "Logarithmic rule and exponentials with subs." },
          { id: "calc_indef_int_trigonometric_with_substitution", name: "Trigonometric with substitution" },
          { id: "calc_indef_int_inverse_trigonometric_with_substitution", name: "Inverse trigonometric with substitution" },
          { id: "calc_indef_int_integration_by_parts", name: "Integration by parts" },
        ],
      },
      {
        id: "definite_integration",
        name: "Definite Integration",
        topics: [
          { id: "calc_def_int_approximating_area_under_a_curve", name: "Approximating area under a curve" },
          { id: "calc_def_int_area_under_a_curve_by_limit_of_sums", name: "Area under a curve by limit of sums" },
          { id: "calc_def_int_riemann_sum_tables", name: "Riemann sum tables" },
          { id: "calc_def_int_first_fundamental_theorem_of_calculus", name: "First Fundamental Theorem of Calculus" },
          { id: "calc_def_int_substitution_with_change_of_variables", name: "Substitution with change of variables" },
          { id: "calc_def_int_mean_value_theorem", name: "Mean Value Theorem" },
          { id: "calc_def_int_second_fundamental_theorem_of_calculus", name: "Second Fundamental Theorem of Calculus" },
        ],
      },
      {
        id: "applications_of_integration",
        name: "Applications of Integration",
        topics: [
          { id: "calc_app_int_area_under_a_curve", name: "Area under a curve" },
          { id: "calc_app_int_area_between_curves", name: "Area between curves" },
          { id: "calc_app_int_volume_by_slicing_disks_and_washers", name: "Volume by slicing, disks and washers" },
          { id: "calc_app_int_volume_by_cylinders", name: "Volume by cylinders" },
          { id: "calc_app_int_volume_of_solids_with_known_cross_sections", name: "Volume of solids with known cross sections" },
          { id: "calc_app_int_motion_along_a_line_revisited", name: "Motion along a line revisited" },
        ],
      },
      {
        id: "differential_equations",
        name: "Differential Equations",
        topics: [
          { id: "calc_diff_eq_slope_fields", name: "Slope fields" },
          { id: "calc_diff_eq_introduction", name: "Introduction" },
          { id: "calc_diff_eq_separable", name: "Separable" },
          { id: "calc_diff_eq_exponential_growth_and_decay", name: "Exponential growth and decay" },
        ],
      },
    ],
  },
];

export function getCurriculumLevel(levelId: string): CurriculumLevel | undefined {
  return CURRICULUM.find((level) => level.id === levelId);
}
