"""Catalog generator type: a2_polynomial_functions_end_behavior_and_general_graph_shape."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_polynomial_functions_end_behavior_and_general_graph_shape")
