param(
  [string]$AppUrl = "http://localhost:3000"
)

$ErrorActionPreference = "Stop"
$stripeCmd = Join-Path $env:APPDATA "npm\stripe.cmd"
$configPath = Join-Path $env:USERPROFILE ".config\stripe\config.toml"
$projectRoot = Split-Path $PSScriptRoot -Parent
$envPath = Join-Path $projectRoot ".env.local"

function Get-EnvValue {
  param([string]$Name)

  if (-not (Test-Path $envPath)) {
    return $null
  }

  foreach ($line in Get-Content $envPath) {
    if ($line -match "^$Name=(.*)$") {
      $value = $matches[1].Trim()
      if ($value) {
        return $value
      }
    }
  }

  return $null
}

function Test-StripeSecretKey {
  param([string]$Key)

  if ($Key -match '^(sk_test_|sk_live_|rk_test_|rk_live_)') {
    return $true
  }

  return $false
}

function Read-StripeKeyFromConfig {
  if (-not (Test-Path $configPath)) {
    return $null
  }

  $config = Get-Content $configPath -Raw
  $key = $null
  if ($config -match 'test_mode_api_key\s*=\s*"([^"]+)"') {
    $key = $matches[1]
  } elseif ($config -match "test_mode_api_key\s*=\s*'([^']+)'") {
    $key = $matches[1]
  }

  if ($key -and (Test-StripeSecretKey $key)) {
    return $key
  }

  if ($key -and $key.StartsWith("mk_")) {
    Write-Host ""
    Write-Host "Stripe CLI returned a merchant key (mk_), which cannot be used server-side."
    Write-Host "Use your secret key (sk_test_...) from the Dashboard instead."
    Write-Host ""
  }

  return $null
}

function Write-EnvFile {
  param(
    [string]$SecretKey,
    [string]$WebhookSecret
  )

  $existingSubscriptionPriceId = Get-EnvValue "STRIPE_SUBSCRIPTION_PRICE_ID"
  $existingAuthSecret = Get-EnvValue "AUTH_SECRET"
  $existingGoogleId = Get-EnvValue "AUTH_GOOGLE_ID"
  $existingGoogleSecret = Get-EnvValue "AUTH_GOOGLE_SECRET"

  $webhookLine = if ($WebhookSecret) { $WebhookSecret } else { "" }
  $subscriptionPriceLine = if ($existingSubscriptionPriceId) { $existingSubscriptionPriceId } else { "" }
  $authSecretLine = if ($existingAuthSecret) { $existingAuthSecret } else { "" }
  $googleIdLine = if ($existingGoogleId) { $existingGoogleId } else { "" }
  $googleSecretLine = if ($existingGoogleSecret) { $existingGoogleSecret } else { "" }

  $envContent = @"
# Generated by scripts/setup-stripe.ps1
STRIPE_SECRET_KEY=$SecretKey
STRIPE_WEBHOOK_SECRET=$webhookLine
STRIPE_PDF_PRICE_CENTS=300
STRIPE_SUBSCRIPTION_PRICE_CENTS=1000
STRIPE_SUBSCRIPTION_PRICE_ID=$subscriptionPriceLine
NEXT_PUBLIC_APP_URL=$AppUrl

# Auth.js (Google OAuth) — required for Pro subscription
AUTH_SECRET=$authSecretLine
AUTH_GOOGLE_ID=$googleIdLine
AUTH_GOOGLE_SECRET=$googleSecretLine
"@

  Set-Content -Path $envPath -Value $envContent -Encoding UTF8
}

if (-not (Test-Path $stripeCmd)) {
  Write-Host "Installing Stripe CLI..."
  npm install -g @stripe/cli | Out-Null
}

$secretKey = Read-StripeKeyFromConfig
if (-not $secretKey) {
  $secretKey = Get-EnvValue "STRIPE_SECRET_KEY"
}

if (-not $secretKey) {
  Write-Host ""
  Write-Host "Stripe CLI is not logged in yet."
  Write-Host ""
  Write-Host "Option A (recommended): in this terminal, run:"
  Write-Host "  stripe login"
  Write-Host "Then run this script again."
  Write-Host ""
  Write-Host "Option B: paste a test secret key from:"
  Write-Host "  https://dashboard.stripe.com/test/apikeys"
  Write-Host ""
  $secretKey = Read-Host "Secret key (sk_test_...)"
  $secretKey = $secretKey.Trim()

  if (-not (Test-StripeSecretKey $secretKey)) {
    throw "Use a secret key starting with sk_test_ or rk_test_ from https://dashboard.stripe.com/test/apikeys"
  }
}

$existingWebhookSecret = Get-EnvValue "STRIPE_WEBHOOK_SECRET"
Write-EnvFile -SecretKey $secretKey -WebhookSecret $existingWebhookSecret

Write-Host ""
Write-Host "Wrote $envPath"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. In a separate terminal, run: npm run stripe:listen"
Write-Host "  2. Copy the whsec_... value into STRIPE_WEBHOOK_SECRET in .env.local"
Write-Host "     (or re-run npm run setup:stripe after listen prints the secret)"
Write-Host "  3. Create a Stripe Product 'Polynomial Pro' with a $10/mo recurring Price,"
Write-Host "     then set STRIPE_SUBSCRIPTION_PRICE_ID=price_... in .env.local"
Write-Host "  4. Add Google OAuth + AUTH_SECRET (see .env.example) for Pro subscriptions"
Write-Host "  5. Restart the dev server: npm run dev"
Write-Host "  6. Test checkout with card 4242 4242 4242 4242"
Write-Host ""

if (-not $existingWebhookSecret) {
  Write-Host "Tip: npm run stripe:listen prints the webhook secret on startup."
}
