"""Catalog generator type: a2_systems_of_equations_and_inequalities_points_in_three_dimensions."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_systems_of_equations_and_inequalities_points_in_three_dimensions")
