from .basic import GENERATORS as _BASIC_GENERATORS
from .calculus import GENERATORS as _CALCULUS_GENERATORS
from .equations import GENERATORS as _EQUATION_GENERATORS
from .geometry import GENERATORS as _GEOMETRY_GENERATORS
from .grade6 import GENERATORS as _GRADE6_GENERATORS
from .graphing import GENERATORS as _GRAPHING_GENERATORS
from .hand_written import GENERATORS as _HAND_WRITTEN_GENERATORS
from .linear import GENERATORS as _LINEAR_GENERATORS
from .misc import GENERATORS as _MISC_GENERATORS
from .numbers import GENERATORS as _NUMBER_GENERATORS
from .algebra2 import GENERATORS as _ALGEBRA2_GENERATORS
from .precalc import GENERATORS as _PRECALC_GENERATORS
from .word_problems import GENERATORS as _WORD_PROBLEM_GENERATORS
from .statistics import GENERATORS as _STATISTICS_GENERATORS
from .advanced import GENERATORS as _ADVANCED_GENERATORS
from .grade_level import GENERATORS as _GRADE_LEVEL_GENERATORS

GENERATORS = {
    **_BASIC_GENERATORS,
    **_NUMBER_GENERATORS,
    **_GRADE6_GENERATORS,
    **_EQUATION_GENERATORS,
    **_LINEAR_GENERATORS,
    **_GRAPHING_GENERATORS,
    **_GEOMETRY_GENERATORS,
    **_MISC_GENERATORS,
    **_HAND_WRITTEN_GENERATORS,
    **_PRECALC_GENERATORS,
    **_ALGEBRA2_GENERATORS,
    **_CALCULUS_GENERATORS,
    **_WORD_PROBLEM_GENERATORS,
    **_STATISTICS_GENERATORS,
    **_ADVANCED_GENERATORS,
    **_GRADE_LEVEL_GENERATORS,
}

__all__ = ["GENERATORS"]
