"""Catalog generator type: a2_radical_functions_and_rational_exponents_rational_exponent_equations."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_radical_functions_and_rational_exponents_rational_exponent_equations")
