"""Catalog generator type: a2_radical_functions_and_rational_exponents_domain_and_range_of_radical_functions."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_radical_functions_and_rational_exponents_domain_and_range_of_radical_functions")
