"""Catalog generator type: a2_relations_and_introduction_to_functions_evaluating_and_graphing_functions."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_relations_and_introduction_to_functions_evaluating_and_graphing_functions")
