"""Catalog generator type: a2_relations_and_introduction_to_functions_discrete_relations."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_relations_and_introduction_to_functions_discrete_relations")
