"""Catalog generator type: a2_exponential_and_logarithmic_expressions_exponents_and_logarithms."""

from question_engine.types._from_generator import register_from_catalog

register_from_catalog("a2_exponential_and_logarithmic_expressions_exponents_and_logarithms")
